### ISSUE TITLE
Реализовать поиск на ES

### ISSUE THREAD

**Issue by Orhideous** [everypony/tabun#1]

**Comment by zluca** [comment]
Могу сделать быстрофикс чтобы поиск шёл по тэгам. Такой функционал в движке Табуна уже есть, достаточно будет простенького инлайн скрипта. Пускай это и костыль, но всё же лучше чем ошибка 403.
А нормальный поиск можно будет сделать когда-нибудь потом, в отдалённом светлом будущем.

В общем, Орхи, нужна отмашка делать или нет?

**Comment by roman901** [comment]
Это мне, это мне

**Comment by roman901** [comment]
Есть минимально работающая версия. Нужно добавить поднятие Эластика и подумать как импортировать существующую базу. Скорее всего написать cli команду.

**Comment by Orhideous** [comment]
@roman901 `ActionOldSearch.class.php` больше не нужен?
Насчет эластика — я добавлю контейнер с ним в `vagga.yaml` и смержу ветку.
Да, CLI для полной переиндексации нужен.

**Comment by roman901** [comment]
@Orhideous да, уже не нужен.
Что из дополительных фишек еще нужно? (расширенное тз)

**Comment by Orhideous** [comment]
#48, думаю.
Надо посмотреть, как он на продакшене по нагрузке будет.

**Comment by roman901** [comment]
Тут только тестить. В теории не больше чем нагрузка на бд

**Comment by Orhideous** [comment]
@roman901 Смотри, на БД сейчас идет несколько типов тяжелых агрегаций, которыми она не должна заниматься в принципе, например [это](https://github.com/everypony/tabun/blob/development/classes/modules/blog/Blog.class.php#L745). На практике эти запросы выглядят как `SELECT … WHERE … IN (<50-300 ids>)`.
Если по производительности будет быстрее, то есть смысл переложить это на ES, а из базы доставать просто по ID.

**Comment by roman901** [comment]
@Orhideous ну уж нет, это как раз то, чем она должна заниматься. Использовать индекс ПОИСКОВЫЙ для левых данных это уже слишком. Проблема в лишь том, что все эти обработки данных (в поиске, кстати, тоже такое есть) слишком уж монструозны и неповоротливы.

**Comment by Orhideous** [comment]
@roman901 Я говорю не о _теории_, а о том, с чем напрямую работал. Я тебе расскажу позже о «монструозности» и неповоротливости индексов.
А так — да, ты прав, как раз левые данные в индексе хранить не нужно.

**Comment by roman901** [comment]
@Orhideous я не про индексы вообще, а конкретно про ls. У меня вчера нехило бомбануло со всего этого кода. А чтоб получать такую инфу из ES ее нужно туда занести. Тобишь индексировать блоги.

**Comment by zluca** [comment]
@roman901 тебе информация к размышлению. В автокомплите по тэгам работают спецсимволы, которые позволяют делать некое подобие регулярок. Вот например:
<img src="https://cdn.everypony.ru/storage/02/43/83/2016/03/23/0072281f0e.png">
Было бы неплохо их к самому поиску приколхозить, ибо броняши тэги прописывают очень креативно (т.е. через круп) :D

**Comment by Orhideous** [comment]
Для обсуждения не стоит переоткрывать issue, можно и так.
@zluca @roman901 Можно ведь сделать подобие fuzzy search на ES, не прибегая к введению спецсимволов, ЕМНИП.

**Comment by roman901** [comment]
@Orhideous можно, но даже морфемный поиск требует задуматься. А так же поиск по части слова. Не в приоритете, но в планах, скорее всего.

**Comment by Orhideous** [comment]
Я замержил ветку и сделал наброски команды для реиндексации — `vagga reindex`, но на объемах Табуна гонять десятки ГБ через Redis медленно.
Как я вижу усовершенствование — передача вместо массива данных `topic_id`/`comment_id` в задачу, а уже на стороне питона там пусть вытаскиваются необходимые данные без какой-либо ORM, чтобы избежать ненужных накладных расходов, в т.ч. на сериализацию, выборку полей и создание объектов.

Дальше, я удалил кеширование результатов поиска; для Sphinx оно ещё как-то выполняло функцию снижения нагрузки, с ES оно тут ни к чему.

Кроме того, заметил, что с выводом результатов поиска в шаблон что-то не то: поиск есть, но результаты не отображаются. @roman901, погляди, пожалуйста…

**Comment by undertroll** [comment]
Лезу не в тот тред вообще, но @Orhideous ты долго еще молчать в ЛС скайпа будешь, черт подери?

**Comment by roman901** [comment]
@Orhideous есть такое. Поиск пока unstable, поэтому мог что-нибудь сломать.

**Comment by Orhideous** [comment]
GUI, в целом, готов. Можно закрывать.

**Comment by NeatSketch** [comment]
This issue was moved to roman901/tabun#1
