### ISSUE TITLE
Выделить явно текст «Автор запретил добавлять комментарии»

### ISSUE THREAD

**Issue by Orhideous** [everypony/tabun#10]

**Comment by zluca** [comment]
Не закрываю пока иссуй. @Orhideous посмотри стили пожалуйста. Пока что выглядит вот [так](https://cdn.everypony.ru/storage/02/43/83/2016/09/12/2c6248f97b.png)

**Comment by Orhideous** [comment]
Неплохо, можно делать пулреквест и мержить.

**Comment by zluca** [comment]
>мержить.

Так я сразу в development branch фигачу. =) или так не надо делать?

**Comment by Orhideous** [comment]
Можно, если это небольшие фиксы в несколько строк кода. Для более серьёзного нужно делать отдельные ветки, как, например, ветка `search`

**Comment by zluca** [comment]
@Orhideous я тут подумал, может стоит аналогичный стиль применить к сообщению "Только зарегистрированные и авторизованные пользователи могут оставлять комментарии."? Он в том же месте располагается, так что было бы логично.

**Comment by Orhideous** [comment]
@zluca См. #49

**Comment by AJFly** [comment]
Точку не забудьте в конце.
