### ISSUE TITLE
Ошибка с отображением "Избранное" на десктопе.

### ISSUE THREAD

**Issue by AJFly** [everypony/tabun#100]
[Вот](http://i.imgur.com/FCBreWy.png).
Но при нажатии (добавление) встает на место. После еще одного нажатия (удаление), тоже все норм.

Код там [такой](http://i.imgur.com/gQKNEs0.png), и место прямо под "Избранное" как бы кликальное (курсор меняется).

**Comment by zluca** [comment]
Хром/Файрфокс всё нормально. @AJFly а у тебя какой браузер? Можешь из разных посмотреть?

**Comment by AJFly** [comment]
@zluca Chrome 51.
___________________
Как ни странно, на Лисе норм. Хромотраблы опять?

**Comment by Orhideous** [comment]
На Chromium 53 не воспроизводится.
Вот что, выделит сбойный элемент в консоли разработчика и переключи на вкладку `Computed`. Мне интересно, как он рисуется.

**Comment by zluca** [comment]
Так как больше ни у кого не воспроизводится закрываю.
