### ISSUE TITLE
jQueri.ui

### ISSUE THREAD

**Issue by zluca** [everypony/tabun#101]
### Проблема

Куча неиспользуемого кода.
[jqueri.ui.js](https://github.com/everypony/tabun/blob/development/frontend/vendor/jquery.ui.js) - 149880
[jquery-ui.styl](https://github.com/everypony/tabun/blob/development/frontend/styles/jquery-ui.styl) - 18221
Реально из всей библиотеки используется только автокомплит. Ещё объявляется datepicker, но где он используется я не нашёл. Скорее всего просто остатки старого кода.
### Решение

Лишние стили поудалять. Из всего файла оставить только несколько строчек про менюшку автокомплита.

По скриптам есть варианты.
- написать свои велосипеды
- или прикрутить библиотеку autocomplete.js отдельно.

Но в любом случае объём прилично снизится.

**Comment by Orhideous** [comment]
@zluca Значит, как я понял, datepicker можно безболезненно удалять.
Что касается автокомплита (в т.ч. тегов при написании поста) — я напишу ТЗ на замену его адекватным компонентом, @s3rious обещался с подобным помочь.

**Comment by zluca** [comment]
В общем после выпиливания datepicker объём библиотеки уменьшился в 2 раза. Остальные компоненты не вырезать из-за зависимостей. Ну и стили я почти в ноль урезал. Думаю дальнейшая оптимизация не даст эффекта, так что закрываю.
