### ISSUE TITLE
Запретить индексировать случайный контент

### ISSUE THREAD

**Issue by NeatSketch** [everypony/tabun#107]
### Зачем?
- Рандомный контент не должен индексироваться
- Невозможно найти источник цитаты, так как в индекс попадает всё подряд
### Как?

Обернуть текст цитаты в:
`<!-- noindex --><!--googleoff: index--> ... <!--googleon: index><!--/ noindex -->`
Работает для роботов Google и Яндекс.

**Comment by zluca** [comment]
Тогда и прямой эфир тоже. И профиля пользователей.

**Comment by roman901** [comment]
И табун целиком

**Comment by undertroll** [comment]
Нет, профии не надо, а вот прямой эфир бы да.

**Comment by zluca** [comment]
@undertroll ещё как надо. Вообще все локации где контент "съезжает" на следующую страницу исключать из индексирования. Это и посты/комменты в профилях, и Активность, и Ленты постов.

По сути на Табуне стабильны только сами топики - вот там ссылка никогда не меняется.

**Comment by undertroll** [comment]
@zluca Я думал ты про описание профиля.

**Comment by Orhideous** [comment]
Случайный контент, действительно не нужно индексировать. Пока только Разум Табуна нужно обернуть в эти комментарии.

**Comment by andreymal** [comment]
@NeatSketch гуглоробот всё равно игнорирует такие комментарии

**Comment by NeatSketch** [comment]
@andreymal Идея: использовать в шаблонах функцию, определяющую бота по юзерагенту, чтобы выключать вывод блоков рандомного контента.
