### ISSUE TITLE
Fix upload of photos and avatars

### ISSUE THREAD

**Issue by zluca** [everypony/tabun#115]
После запиливания логов посмотрел что же там не работает:

>  errors tabun-trunk [03-Mar-2017 09:06:59 Europe/Moscow] PHP Fatal error: Call to undefined function imagecreatefromjpeg() in /app/engine/lib/external/LiveImage/Image.php on line 151 

Значит аватарки были поломаты 2 раза: со стороны фронта (это я починил) и со стороны сервера. Видимо функции imagecreatefromjpeg(), imagecreatefromgif(), imagecreatefrompng() где-то объявлялись, а потом этот код выкинули. Но где именно я не нашёл.

@Orhideous в общем будет время посмотри.

**Comment by zluca** [comment]
@Orhideous  Функция  imagecreatefrompng() также использовалась в модуле kcapture. Может ты чего лишнего выкинул когда выпиливал?

**Comment by zluca** [comment]
В общем небольшое гугление показало что искомая функция является частью GD library. Народ на стэковерфлове пишет что либо она не установлена, либо скомпилирована с неправильными флагами. @Orhideous тебе уже всё раскопали и на блюдечке поднёсли давай чини уже. 😃

**Comment by Orhideous** [comment]
Что я и делаю. Фронтенд, между прочим, уже готов в ветке avatars. Остался бекенд.

**Comment by zluca** [comment]
> уже готов

На транке вся статика отвалилась. :/

**Comment by Orhideous** [comment]
Исправил.

**Comment by Orhideous** [comment]
По бекенду там я посмотрел, будет капитальное упрощение, и отказ от GD. Вдобавок, как ни странно, поддержка анимированных аватарок из коробки.

**Comment by zluca** [comment]
> поддержка анимированных аватарок из коробки

А оно точно надо? У нас в комментах аватарки 24х24 да ещё уменьшенные до 18, там всё равно ничего видно не будет, только лишняя нагрузка на проц.

**Comment by Orhideous** [comment]
Ну оно просто есть и всё. Среди прочих поддерживаемых форматов. ¯\_(ツ)_/¯

**Comment by Orhideous** [comment]
Fixed in #182
