### ISSUE TITLE
Загружать изображения (кроме смайликов) и iframe в спойлерах только при раскрытии спойлера

### ISSUE THREAD

**Issue by Farxial** [everypony/tabun#118]

**Comment by zluca** [comment]
Пока работает только в комментах и только для картинок. С ифреймами надо со стороны сервера ковыряться.

**Comment by zluca** [comment]
Работает в топиках, письмах, комментах. Но пока только картинки.

**Comment by Farxial** [comment]
Ня ![25161c.png](https://files.everypony.ru/smiles/b8/7f/25161c.png)
> С ифреймами надо со стороны сервера ковыряться.

Фыыр ![c7f70b.png](https://files.everypony.ru/smiles/63/9c/c7f70b.png)

**Comment by zluca** [comment]
Перенёс видеопарсер на сторону клиента, ибо в пхп я не шарю. Заодно починил рутуб. Глюков не замечено <s>наверное</s> , так что закрываю.
