### ISSUE TITLE
PHP 7: session_regenerate_id(): Cannot regenerate session id - session is not active

### ISSUE THREAD

**Issue by andreymal** [everypony/tabun#142]
В моём виртуалбоксе после выкатывания https://github.com/everypony/tabun/pull/141 сыпет в логах на каждый запрос:

    session_regenerate_id(): Cannot regenerate session id - session is not active in tabun/engine/modules/session/Session.class.php on line 77

Не исключено, что я что-то криво выкатил, но вдруг свежепоявившийся баг

При этом изменения поведения сайта как-то не замечено, вход-выход работает нормально (кроме галочки «Запомнить меня», но это старый баг)

**Comment by KarelWintersky** [comment]
Самый простой вариант - где-то у нас в коде затесался файл с BOM
Он вставляется перед всем выводом, еще до посылки заголовков и... и вот.

**Comment by andreymal** [comment]
@KarelWintersky тогда бы вопило headers already sent

Тем не менее проверил php-файлы — все без BOM

**Comment by KarelWintersky** [comment]
Я посмотрел в сети. Проблема вроде как более или менее известная, но решения нет. И причин "почему оно так" - тоже нет :(

**Comment by KarelWintersky** [comment]
Так-с.
Это не у нас, это в зенд-фреймворке, похоже:

https://github.com/zendframework/zend-session/issues/70
https://github.com/zendframework/zf1/issues/659
https://stackoverflow.com/questions/21496966/cannot-regenerate-session-id-zend-framework-2

Честно говоря, зачем в движке используется ZendFramework v2 для меня загадка :(

**Comment by andreymal** [comment]
(вообще с zend тоже какая-то фигня, травис с ваггой сильно ругается варнингами, я не умею разбираться в этом)

**Comment by KarelWintersky** [comment]
Травис на всё ругается кроме идеально написанного кода. 

К слову, я пытался развернуть травис у себя на сервере. Гиблое дело!

**Comment by KarelWintersky** [comment]
Кажется, я знаю решение. В рамках этого переоткрываю issue.

**Comment by Orhideous** [comment]
Fixed by 717e4762d474759ca15147b84414a202b34525e4
