### ISSUE TITLE
Multiple mapping types are not supported in indices created in Elasticsearch 6.0

### ISSUE THREAD

**Issue by andreymal** [everypony/tabun#147]
https://www.elastic.co/guide/en/elasticsearch/reference/6.0/removal-of-types.html

В общем, сейчас Celery, индексирующий поиск, падает с ошибкой:

>elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception', 'Rejecting mapping update to [tabun] as the final mapping would have more than 1 type: [topic, comment]')

Я так понимаю, нужно разделить один индекс на несколько, но php-код приколочен к строго одному индексу, так что я ой всё

**Comment by roman901** [comment]
@andreymal а) всё писалось под эластик 2.3, б) нужно вливать начальную конфигурацию для коррентного индекса, которую что я, что Орхид потеряли =)

**Comment by Orhideous** [comment]
Resolved in https://github.com/everypony/tabun/commit/9418edcd6e7512c0c61f47265567cd14146ac639
