### ISSUE TITLE
Неверное ограничение количества символов в поле редактирования

### ISSUE THREAD

**Issue by Orhideous** [everypony/tabun#15]
Написано 3k, но реально ~35k

**Comment by zluca** [comment]
Блин у меня ж Вестник Кармаклоппера на 50к символов, придётся резать. =))

**Comment by roman901** [comment]
А какое вообще ограничение нужно? Не мало ли 3к, может хотя бы 6 сделать?

**Comment by zluca** [comment]
>А какое вообще ограничение нужно?

Ну я подумал что 3к и нужно. =) На всякий случай переоткрою, пускай Орхид сам посмотрит.

**Comment by Orhideous** [comment]
Вообще, надо как раз чуть меньше Unsigned smallint, хватит как раз **65534**
@zluca, пройдись по местам парсинга текста и сделай проверку. Да, константу длины текста вынеси в `config.php`
