### ISSUE TITLE
Replace bundled FontAwesome with packaged version

### ISSUE THREAD

**Issue by Orhideous** [everypony/tabun#160]
Technical debt after #158

**Comment by Farxial** [comment]
>  1. hint. В npm  5я версия (как хочет @Farxial) называется не [fontawesome](https://www.npmjs.com/package/font-awesome-webpack-4), а [fontawesome-free](https://www.npmjs.com/package/@fortawesome/fontawesome-free).

Спасибо) Но я уже сделал, просто жду, когда вернётся Орхи... Но, если этот вопрос волнует и других - OK, скину сейчас ![https://files.everypony.ru/smiles/2e/c2/db96ba.png](https://files.everypony.ru/smiles/2e/c2/db96ba.png)

> 2. Раз уж я вам не авторитет [почитайте](https://fontawesome.com/how-to-use/on-the-web/other-topics/performance) что пишут сами авторы фа, вебфонты не для Табуна.

Из того текста мне понятно лишь, что плохим вариантом является **SVG with JavaScript**.
В любом случае - что ты предллагаешь? Вернуть SVG? Мб го голосование? (Лично мне так почти пофиг, просто вариант с веб-шрифтом, не важно, FA или нет, мне кажется более "чистым".)

**Comment by zluca** [comment]
> В любом случае - что ты предллагаешь?

Отдельные svg иконки прописать ручками в css.

**Comment by Farxial** [comment]
OK, я нашёл CSS свойство `mask`, работающее с URL. [В MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/mask) указана хорошая поддержка браузерами `mask`, в отличие от [mask-image](https://developer.mozilla.org/en-US/docs/Web/CSS/mask-image). А вот на странице `mask-image` внизу есть указание того, что поддержка SVG экспериментальна (![https://developer.mozilla.org/static/general/flask.6c6c1a459b56.svg](https://developer.mozilla.org/static/general/flask.6c6c1a459b56.svg)). Хотя, может, это ничего и не значит в данном случае - я точно не знаю. [На caniuse.com](https://caniuse.com/#search=mask) данные не впечатляют, но, с другой стороны, *настолько* старые браузеры Табуном итак могут не поддерживаться с большой вероятностью.
Также можно попробовать использовать `mask` и `mask-image` одновременно.
Что думаешь на счёт этого?
Может, есть смысл сделать на Табуне опрос (с ссылкой на страницу, где будет нужная иконка)? Или можно сказать о поддержке заочно?

**Comment by zluca** [comment]
> на Табуне опрос

Лучше спроси у Орхи или Рандома статистику.

**Comment by zluca** [comment]
Те у кого адблоки на интернет эксплорерах не сидят, так что у них априори всё заработает.

**Comment by zluca** [comment]
@Farxial 
Так насчёт mask. По стандарту это должен быть просто шортхенд для mask-* свойств, но реально по стандарту работает только ФФ 53+. Причина насколько я понимаю в том что производители браузеров сначала повнедряли mask кто как хотел, а только потом сели стандарт писать (обычная ситуация). В результате поддержка mask хоть и шире, но там всё через жопу и надо каждый отдельный браузер проверять и желательно разные версии. Так что я бы лучше не mask использовал, а отдельные mask-* свойства.

**Comment by andreymal** [comment]
@zluca по имеющимся у меня данным с IE11 пытаются заходить всего 1.2% народа, c Firefox 52 внезапно набралось 1.7%, с Edge 0.75%, Chrome 49 0.8%, с UC Browser 0.6%, с Opera Mini 0.4%, Pale Moon 0.3%, а на остальных плевать наверно

В общем и целом 77% народа юзают хром и скины к нему типа яндекс-браузера, 18% фаерфокс, 5% сафари, остальное по мелочи (в сумме 107%, потому что с нескольких айпишников юзали несколько разных браузеров, такие дела)

**Comment by andreymal** [comment]
Ах да, целых 2.4% сидят с Windows XP и целых 3.5% с линукса

**Comment by zluca** [comment]
@andreymal это с tabun.andreymal.org? Так к тебе более продвинутые пользователи заходят, на Табуне может быть больше ретроградов. =)

**Comment by andreymal** [comment]
@zluca из автовестника, в нём тоже стоит зонд 🌚

**Comment by zluca** [comment]
Ну раз так, то можно дропать поддержку старого рожна и не заморачиваться.

**Comment by Farxial** [comment]
> @Farxial
> Так насчёт mask. По стандарту это должен быть просто шортхенд для mask-* свойств, но реально по стандарту работает только ФФ 53+. Причина насколько я понимаю в том что производители браузеров сначала повнедряли mask кто как хотел, а только потом сели стандарт писать (обычная ситуация). В результате поддержка mask хоть и шире, но там всё через жопу и надо каждый отдельный браузер проверять и желательно разные версии. Так что я бы лучше не mask использовал, а отдельные mask-* свойства.

OK, спасибо за объяснение.
Пичалька, если в браузерах реализовано плохо. (Хотя где можно накосячить с единственным вариантом - url с картинкой? Разве что отсутствием поддержки SVG...)
Ну, я заюзал сразу `-webkit-mask`, `mask`, `mask-image`. Надеюсь, всё будет норм.
Но если нет, мы это потом узнаем и можно будет подправить (возможно, но это уже зависит от того, не перейдёт ли разработка снова в режим спячки) ![https://files.everypony.ru/smiles/9f/42/00b2a6.png](https://files.everypony.ru/smiles/9f/42/00b2a6.png)
Да, в идеале надо проверять на всех браузерах, но это пока для меня слишком ![https://files.everypony.ru/smiles/6b/f6/13e0e4.png](https://files.everypony.ru/smiles/6b/f6/13e0e4.png)

**Comment by Farxial** [comment]
На счёт статистики - спасибки вам за совет и инфу ^^

**Comment by Orhideous** [comment]
Need to triage this issue. IIRC, there were no visible problems in the new browsers already at time of #162.
@Ponywka Can you please check if FA icons are displaying without glitches?

**Comment by Ponywka** [comment]
> Can you please check if FA icons are displaying without glitches?
Они сейчас вообще не отображаются. Пока что не знаю в чем проблема, надо разбираться

![image](https://user-images.githubusercontent.com/26777464/144240444-3f18b3c7-f001-4b38-a964-f21670f8f815.png)

**Comment by Ponywka** [comment]
Upd. Похоже это место вообще не под иконку было, а прямого использования Font Awesome я не нашел
( Намекнул на это @intelrug )

**Comment by Ponywka** [comment]
Upd. 2: Иконки как оказалось есть, только нигде не используются. Если ручками прописать их, то они отображаются:

![image](https://user-images.githubusercontent.com/26777464/144242556-24bed9c2-517d-40f0-92f2-7c1db5054d6b.png)

**Comment by Orhideous** [comment]
Thats… weird. Somehow this slipped my mind.

And one more thing: despite that translations exists
https://github.com/everypony/tabun/blob/ef360dd0ea8d856bdefb98b036a1dd4583ef3e87/templates/skin/synio/locale/ru_RU/LC_MESSAGES/parts/common.po#L20-L21
and `{t}` tags used
https://github.com/everypony/tabun/blob/ef360dd0ea8d856bdefb98b036a1dd4583ef3e87/templates/skin/synio/topic_part_footer.tpl#L38
content rendered untranslated. Seems like bug to me.

**Comment by intelrug** [comment]
Получается можно закрыть эту issue? Иконки работают, вроде бы. Дальше в планах #106 ?

**Comment by Orhideous** [comment]
@intelrug If so, indeed. Closing as fixed.
