### ISSUE TITLE
Не работает выравнивание в постах

### ISSUE THREAD

**Issue by Orhideous** [everypony/tabun#17]

**Comment by zluca** [comment]
Свойство align теперь deprecated поэтому в новых браузерах и не работает. Самое простое решение добавить css стиль:
```
  [align="left"]{
    display: block;
    text-align: left;
  }
  [align="right"]{
    display: block;
    text-align: right;
  }
  [align="center"]{
    display: block;
    text-align: center;
  }
```
Если же требуется реализовать обтекание то:
```
  [align="left"]{
    float: left;
  }
  [align="right"]{
    float: right;
  }
  [align="center"]{
    display: block;
    text-align: center;
    clear:both;
  }
```
Конечно, лучше было бы совсем избавиться от алигна заменив его классами типа .text-align-rigth .text-align-center, но это надо лезть в дебри.

**Comment by andreymal** [comment]
До августа 2015-го работало, браузеры тут ни при чём.

**Comment by zluca** [comment]
Оказалось ещё нужно выравнивание по высоте. В частности оно используется в [Автовестнике](https://tabun.everypony.ru/blog/apc/163189.html)
### Решение
Либо вернуть align для картинок, либо (что лучше) добавить класс .h-top{vertical-align:top}
