### ISSUE TITLE
Fix `Warning: count()` on all pages

### ISSUE THREAD

**Issue by Ponywka** [everypony/tabun#183]
На некоторых страницах если в PHP включено отображение ошибок выскакивает `Warning: count()`, что в свою очередь ломает скрипты.

Как пример, по адресу http://localhost:8000/question/add
![image](https://user-images.githubusercontent.com/26777464/143959866-3d2b5183-afb4-4bec-869b-124093ab5850.png)

**Comment by Orhideous** [comment]
https://github.com/everypony/tabun/blob/f337082037382756b5ddfddc1c893e1fc3cc4ab7/templates/skin/synio/actions/ActionQuestion/add.tpl#L32-L32
Maybe, `$_aRequest` is empty or not set?

**Comment by Ponywka** [comment]
https://github.com/everypony/tabun/tree/fix/count

**Comment by Ponywka** [comment]
https://github.com/everypony/tabun/pull/197
