### ISSUE TITLE
Search page styles

### ISSUE THREAD

**Issue by Ponywka** [everypony/tabun#184]
На странице поиска стили (Bootstrap'а?) ломают часть стилей самого сайта

![image](https://user-images.githubusercontent.com/26777464/143960293-f1cbb08a-2098-4afe-b6eb-2dfabd87806d.png)

**Comment by Orhideous** [comment]
If I remember correctly, it happens due to leaking styling indeed.
By the way, my decision to use bootstrap became mistake at best and technical debt at worst.

**Comment by Orhideous** [comment]
I see no other viable alternatives other than abandoning bootstrap at all here.
