### ISSUE TITLE
Невозможно добавить/удалить новый контакт в настройках

### ISSUE THREAD

**Issue by Orhideous** [everypony/tabun#21]
## Воспроизведение
-  войти на сайт под своим логином
- нажать на ссылку "Настройки"
- спуститься ниже к блоку "Контакты"
- нажать "Добавить"
### Ожидаемое поведение

Откроется новое drop-down-меню с выбором соц. сети и поле для заполнения ника/линка
### Результат

При нажатии "Добавить" страница поднимается наверх, меню и поле не открываются.
В консоли JS появляется ошибка
`Uncaught TypeError: ls.userfield.removeFormField is not a function` / `Uncaught TypeError: ls.userfield.addFormField is not a function`

**Comment by zluca** [comment]
Итак, провёл я тут небольшое расследование. И вот что выяснилось:

Объект ls.userfield пустой, то есть все функции из [userfield.coffee](https://github.com/everypony/tabun/blob/development/frontend/scripts/app/userfield.coffee) не работают. 
Но при этом сам код этих функций в main.bundle.js присутствует, просто не зарегистрирован где положено.

Предполагаю что ошибка возникает где то на этапе сборки кофе скриптов в нормальный жс скрипт.
routes.userfields: "/admin/userfields/" - возможно из-за этого роута данные функции считаются админскими и не доступны простым юзерам?
В общем дальше я вряд-ли продвинусь, так как плохо представляю себе процесс сборки.

**Comment by Orhideous** [comment]
Спасибо за исследование!

**Comment by undertroll** [comment]
Чинит это Эпик. Ты там своим занимайся.

**Comment by Orhideous** [comment]
А, хорошо.

**Comment by zluca** [comment]
@EpicMan2 проверил - работает. Закрываю иссуй.

**Comment by lunavod** [comment]
При сохранении контактов они просто стираются, десу. Вообще все.

**Comment by zluca** [comment]
Интересно что на старой версии Табуна не стирались. Скорее где-то при валидации формы со стороны сервера косяк.

**Comment by zluca** [comment]
Скорее всего при разбиении конфига на отдельные файлы потеряли строчку. По крайней мере это объясняет почему у меня на старом Табуне всё работало.
