### ISSUE TITLE
Создание ACL

### ISSUE THREAD

**Issue by Orhideous** [everypony/tabun#24]
Необходимо сформировать ACL для следующих правил, применимых к сущностям User, Topic, Comment, Blog
## Модераторы блогов
- Посты:
  - [ ] перенос постов из подотчетного блога
    - [x] в личный блог автора
    - [ ] в черновики автора
  - [ ] редактирование
- Пользователи:
  - [ ] ограничение доступа на запись в блог пользователям
  - [ ] бан пользователей в блоге
- Комментарии:
  - [ ] Удаление комментариев
## Администраторы блогов
- Все права модераторов
- Посты:
  - [ ] удаление
- Пользователи:
  - [ ] изменение состава модераторов блога
- Комментарии:
  - [ ] Изменение комментариев
# Заметки

Под удалением сущности следует подразумевать смену статуса, см. #6

**Comment by NeatSketch** [comment]
Последний пункт зависит от #3

**Comment by NeatSketch** [comment]
@Orhideous 
> - ограничение доступа на запись в блог пользователям
- бан пользователей в блоге

В чём отличие?

**Comment by roman901** [comment]
Наверное в том, что при бане нельзя вообще смотреть контент?

**Comment by zluca** [comment]
Скорее раздельные ограничения на комментарий и пост.

**Comment by NeatSketch** [comment]
Итак, в блогах должны быть следующие категории прав:
- Администратор
- Модератор
- Участник (может писать посты и комментировать)
- Читатель (может комментировать)
- Забаненный (не может писать ничего; если блог закрытый, не может читать)

Верно?

**Comment by Orhideous** [comment]
Верно. Дополню:
* [ ] читатели не могут голосовать;
* [ ] забаненные в открытых блогах не могут комментировать и голосовать (т.е. права незарегистрированного пользователя);

**Comment by NeatSketch** [comment]
> читатели не могут голосовать

Это почему? Если они могут комментировать, то почему бы им не голосовать?

**Comment by zluca** [comment]
В общем как я понимаю должно быть так:
>  ограничение доступа на запись в блог пользователям

Кик из блога без права перевступления. Если блог открытый, то писать комменты и голосовать(?) можно, посты нельзя.
>  бан пользователей в блоге

Ничего нельзя. Если блог открытый то ридонли, как у анонима.

Для закрытых блогов кик == бан.

**Comment by Orhideous** [comment]
@NeatSketch 
> > читатели не могут голосовать

> Это почему? Если они могут комментировать, то почему бы им не голосовать?

Это напрямую следует из
> Читатель (может комментировать)

Значит, только комментировать.

**Comment by zluca** [comment]
> Значит, только комментировать.

Тогда чтобы голосовать придётся вступать в блог. Что-то мне эта идея на нравится.

**Comment by NeatSketch** [comment]
@Orhideous
Я этого не понимаю. Читатели будут вынуждены оценивать топики только через комментарии.
Я думал, что эта категория нужна для ограничения добавления контента в блог, но получается, что она ещё будет запрещать оценивать контент. Не вижу логики.
Оценки я вижу равнозначными комментариям: обе вещи — способы фидбека для топиков.

**Comment by Orhideous** [comment]
@NeatSketch Похоже, мы друг друга не поняли.

По порядку.

Категория читателей может только читать контент: иметь доступ в закрытые блоги, читать топики и комментарии — это очевидно. Read only.

Категория участников может менять контент в блогах: постить новый контент в блоги (топики/комментарии), голосовать за топики либо комментарии в них.

@zluca 
> Тогда чтобы голосовать придётся вступать в блог. Что-то мне эта идея на нравится.
Это верно только в случае, если изначально пользователь принимается в блог *читателем*.

Мое предложение основывалось на необходимости *понижать* уровень доступа к открытым/закрытым блогам, не закрывая в них доступ вообще.

Side note
------------
…реализовать автоматическое добавление участника в открытый блог при первом комментарии?

**Comment by zluca** [comment]
> Мое предложение основывалось на необходимости понижать уровень доступа к открытым/закрытым блогам, не закрывая в них доступ вообще.

Так может сделать раздельные баны на разные операции? Бан на комметы, бан на голосования, бан на посты.

> реализовать автоматическое добавление участника в открытый блог при первом комментарии?

Тогда вся подписка на блоги быстро захламится. К тому же по всем блогам начнут бегать юзеры с первокомментами. Боюсь от таких нововведений начнётся конкретный шитсторм. :D

**Comment by Orhideous** [comment]
> Тогда вся подписка на блоги быстро захламится. К тому же по всем блогам начнут бегать юзеры с первокомментами
Гм. В таком случае, гранулярные ограничения — то, что надо. @NeatSketch ?

**Comment by NeatSketch** [comment]
- [Вариант первый](https://docs.google.com/spreadsheets/d/135fnqevgSGDMOkYLPI9zfWhBXiZG2BKxkr9E0qnq4M0/edit?usp=sharing)
- [Вариант второй](http://i.imgur.com/8yjy30b.png)

**Comment by zluca** [comment]
Вот что я надумал. У нас ведь получается есть куча разных механизмов влияющих на права пользователя совершать те или иные действия. Карма, членство в блоге, баны, плюс блог может быть закрытый или открытый. Всё это не может не конфликтовать. Например, сейчас можно голосовать в закрытом блоге не состоя в нём, потому что за голосование отвечает карма, а она не в курсе что блог закрытый.
Что если сделать один универсальный механизм?

Вот как это может выглядеть:
В настройках блога 2 ряда чекбоксов - правила для простого юзера и для участника блога.
5 прав - читать, голосовать, комментировать, создать пост, вступить. Соответственно разные наборы правил позволяют реализовать и закрытые и полуоткрытые блоги и вообще всё что хочешь. У анонима права только на чтение как для простого юзера.
В профиле пользователя те же 5 чекбоксов чтобы выставить лично ему запреты/разрешения, независимо от того состоит он в блоге или нет. У персональных правил высший приоритет.

Правда трудоёмкость таких изменений я оценить не могу, смотрите сами.

**Comment by Orhideous** [comment]
@zluca, ты только что пришел к тому же мнению, что и я с @NeatSketch :+1:

**Comment by roman901** [comment]
Ощущение будто вы хабр делаете

**Comment by undertroll** [comment]
Вы, главное, потом мне адекватный список дайте изменений если они кардинальные в системе. А то мне еще перепиливать FAQ придется и правила под это дело.

**Comment by Orhideous** [comment]
@undertroll Это просто расширение возможностей, под капотом — стандартные ACL на CRUD для указаных в первом посте сущностей.

**Comment by NeatSketch** [comment]
https://github.com/NeatSketch/tabun/commit/eec5763ea1a9fea84e748e4f793bad1786c56205
см. пояснения в комментариях к коммиту

**Comment by Orhideous** [comment]
@NeatSketch посмотрел, нормально вполне. За сегодня~завтра я замержу ветку `editable_comments`, ориентируйся на этот срок.

**Comment by undertroll** [comment]
@NeatSketch 
Ты можешь в ЛС заглянуть ВК или так и будем в молчанку играть?
