### ISSUE TITLE
Добавить возможность редактирования комментариев

### ISSUE THREAD

**Issue by Orhideous** [everypony/tabun#3]

**Comment by lunavod** [comment]
Там это, овнер блога не может комменты редактировать.

**Comment by undertroll** [comment]
Ждите ACL, блин.

**Comment by lunavod** [comment]
А чего ждать? Раз редактирование впилили, оно и работать нормально должно.

**Comment by undertroll** [comment]
Хотя бы потому, что есть 100500 багов более важных, а до ACL с 1.4. рукой подать?
В первую очередь правим другое некоторое дерьмо.
