### ISSUE TITLE
Не работает кат в опросах

### ISSUE THREAD

**Issue by zluca** [everypony/tabun#30]
Древняя багофича Табуна - при создании опроса кат не работает как положено. Вместо короткой аннотации в ленту попадает весь текст топика.

**Comment by zluca** [comment]
Недофикшено. Надо ковырять ActionQuestion.class.php

**Comment by zluca** [comment]
YaY!! На транке заработало.
<img src="https://cdn.everypony.ru/storage/02/43/83/2016/10/20/aebb1ae944.png" />

@Orhideous  А можно как-нибудь этот коммит отдельно смержить в хотфикс?

**Comment by AJFly** [comment]
Подтверждаю - на десктопе тоже норм.

**Comment by Orhideous** [comment]
Да, можно.
