### ISSUE TITLE
Кнопка обновления комментариев на мобильных устройствах

### ISSUE THREAD

**Issue by undertroll** [everypony/tabun#34]
Должна быть "прилеплена" справа, а не по центру болтаться

**Comment by roman901** [comment]
Текущая реализация никуда не годится. Можно попробовать переписать чтоб было без каких-либо вычислений.

**Comment by undertroll** [comment]
Решать не мне, конечно, но такой вопрос, если переписать, то эта вот хреновина (скрипт) отвалится?
http://pastebin.com/fhKaYtZz

**Comment by roman901** [comment]
Могу сделать минимальными потерями, как доберусь до рабочей станции займусь

**Comment by Orhideous** [comment]
@roman901 Есть подозрения, что [текущая реализация](https://github.com/everypony/tabun/blob/development/frontend/scripts/app/comments.coffee#L100-L133) медленная? Мне очень интересны идеи, как ещё ускорить ее.

**Comment by roman901** [comment]
Я про рендер. Есть идеи как переделать.

**Comment by Orhideous** [comment]
А, понял. Поделись в общих чертах?

**Comment by roman901** [comment]
Внезапно глупо-быстрофикс нарисовался.

**Comment by zluca** [comment]
Там народ жалуется что кнопка улетает на мобилах. Предлагаю откатить [0bedcb5](https://github.com/everypony/tabun/commit/0bedcb50a92e0309f1e027cbeedadb80d818b114)

**Comment by roman901** [comment]
Я починю.

**Comment by zluca** [comment]
Ну смотри сам. Просто я в своём [бранче](https://github.com/everypony/tabun/tree/responsive-design) вообще эту функцию выпилил.

**Comment by zluca** [comment]
> commented 2 days ago
Я починю.


@roman901 может всё-таки откатить? =)

**Comment by roman901** [comment]
@zluca я делаю, у меня небольшие проблемы с девпроцессом :D

**Comment by roman901** [comment]
Как я понимаю уже не нужно?

**Comment by zluca** [comment]
На дев ветке не нужно. На хотфикс надо что-то придумать чтобы прям щас залить на Табун.

**Comment by AJFly** [comment]
Ну как бы улетает еще...

**Comment by roman901** [comment]
У меня теперь адаптивный по умолчанию, не знаю как теперь тестить :D

**Comment by undertroll** [comment]
@roman901 @zluca 
И что, фикса не будет? Серьезно? Юзеры уже немного достали меня спрашивать ЧЗХ с кнопкой, хотя ворчать имеют полное право, ибо это зашквар.

**Comment by roman901** [comment]
Откатите коммит тогда

**Comment by zluca** [comment]
@Orhideous приди,
коммит 0bedcb5 откати!

**Comment by roman901** [comment]
Орхида не будет до понедельника.

**Comment by Orhideous** [comment]
Я коммит откатил в хотфиксе, но как быть с текущим положением дел в `development`? Коммит 0bedcb50a92e0309f1e027cbeedadb80d818b114 затрагивает участки кода в `toolbar.coffee`, которые коммитом 37e6d7c95123c81dcd58fd819ca9f24e37c3b608 удалены.
Там конфликт, и мне надо помощь ~~зала~~ @zluca :smile:

**Comment by zluca** [comment]
@Orhideous в дев не надо ничего трогать. Там тулбар стилями прибит и ничего не вычисляется. Это раньше при горизонтальной прокрутке была необходимость позицию пересчитывать, а теперь ширина всегда 100% экрана.

**Comment by undertroll** [comment]
Что с этим issue теперь вообще? Оно сделано за счет адаптивного дизайна или как?

**Comment by zluca** [comment]
Ломающий коммит откатили, но на сервере пока не откаченная версия стоит.
А адаптивный дизайн в 1.4 только будет.

**Comment by zluca** [comment]
> Мне очень интересны идеи, как ещё ускорить ее.

@Orhideous Я тут как раз засел за литературку по оптимизации js. Так вот оказывается 'use strict' даёт ускорение, по моим тестам выходит где-то 20-25% в функции toggleEditForm
