### ISSUE TITLE
Исправить баг с бегущими понями на моб. устройстве 

### ISSUE THREAD

**Issue by undertroll** [everypony/tabun#36]
Видно только 4, 5 переносится на новую строку и видно от нее только пара пикселей

**Comment by lunavod** [comment]
Может, лучше их вообще через flex сделать? Так, мне кажется, лучше выглядит.
![image](https://cloud.githubusercontent.com/assets/14801311/18684836/56bed872-7f7e-11e6-8103-8b81b81b3e90.png)
![image](https://cloud.githubusercontent.com/assets/14801311/18684849/6763758e-7f7e-11e6-968b-e0fe894a18c9.png)
```
    display: flex;
    flex-wrap: wrap;
    justify-content: space-around;
    overflow: hidden;
    width: 100%;
    margin-bottom: 10px;
```

**Comment by undertroll** [comment]
@lunavod Флексбоксы не везде работают, не во всех браузерах.

**Comment by lunavod** [comment]
@undertroll А в них будут отображаться как сейчас, так что ничего не теряем. *пожал плечами*

**Comment by Orhideous** [comment]
Правильней использовать media queries.

**Comment by lunavod** [comment]
@Orhideous это если делать только к мобильным. А с флексбоксом оно и на больших экранах лучше отображается, ибо растягивает с равными промежутками по всей строке, что выглядит лучше чем когда они просто сжаты в углу, а за ними куча пространства, нет?

**Comment by Orhideous** [comment]
@lunavod Я к тому, что при определенной ширине экрана показывать только N поней. От двух до пяти, например, через `:nth-child`

**Comment by roman901** [comment]
Флекспокс работает во всех относительно свежих браузеров. На моей практике только ie старых версий выделывался, а с остальными браузерами все норм. Flex самое то

**Comment by zluca** [comment]
В общем так как вы ни до чего не договорились сделал по своему. Всех поняш подровнял по высоте под 50 px и сам блок #running_ponies тоже 50px. Даже если потом делать флексы лучше чтобы были ровные картинки.

**Comment by undertroll** [comment]
Оно как будет выглядеть?

**Comment by zluca** [comment]
Т.е. лишние пони слазят вниз, но так как overflow=hidden их не видно и голова не торчит. По крайней мере у меня в браузере так. =) Это я подсветил через инспектор элементов &darr;
<img src="https://cdn.everypony.ru/storage/02/43/83/2016/09/30/c0756d9bd9.png" />

**Comment by zluca** [comment]
Оказывается при масштабировании картинки шакалятся и есть такие деятели на Табуне которые их под микроскопом рассматривают и пишут претензии. :D

В общем отменил свои предыдущие коммиты и переделал на media queries.
