### ISSUE TITLE
Исправить вид бейджа у "Сообщения" в хедере

### ISSUE THREAD

**Issue by roman901** [everypony/tabun#37]
Очень нехорошо смотрится.

**Comment by lunavod** [comment]
Не знаю, что там поправили, но его теперь просто нет. 
![2016-10-17 17-33-42](https://cloud.githubusercontent.com/assets/14801311/19442035/92b9aaa6-9490-11e6-827c-13bc55862f9a.png)

**Comment by zluca** [comment]
`-    top -3px` из-за этого поломаться не могло. Просто сервер вообще тормозит, на почту оповещалки поздно приходят и новые сообщения не сразу отображаются.

**Comment by lunavod** [comment]
М, окей. Просто само сообщение показывается, а бэйджа нет.
