### ISSUE TITLE
Оснастить UI блогов информацией о правах пользователя в блоге

### ISSUE THREAD

**Issue by NeatSketch** [everypony/tabun#40]
- Модераторы и администраторы будут видеть свои роли
- Забаненный пользователь сможет нормально видеть, что он забанен

<img src="https://cloud.githubusercontent.com/assets/8350625/18454443/18e3249a-794d-11e6-901a-2fa1e88d07cc.png" width="300" />

**Comment by zluca** [comment]
@NeatSketch Кроме того надо бы явно обозначить различие полузакрытых блогов от закрытых.

1. В списке блогов добавить кнопку "вступить" для полузакрытых:
<img src="https://cdn.everypony.ru/storage/02/43/83/2016/09/23/9fdc130a7b.png" />
2. В УИ самого блога заменить сообщение

> Это закрытый блог, у вас нет прав на просмотр контента
 
на
> Это полузакрытый блог, вы должны вступить прежде чем просматривать содержимое.

3 Возможно для закрытых также удалить кнопку "Вступить" до получения инвайта.

**Comment by zluca** [comment]
Пофикшено.
