### ISSUE TITLE
Комментарии с низким рейтингом не скрываются

### ISSUE THREAD

**Issue by zluca** [everypony/tabun#43]
Комментарии с рейтингом -5 и ниже получают класс .comment-bad, но он сейчас ни на что не влияет. Вопрос: так и задумано или это недоработка?
Могу сделать стиль чтобы содержимое коммента скрывалось и отображалось по наведению мыши.

**Comment by Orhideous** [comment]
Они действительно раньше скрывались. Можно делать как на хабре — малозаметными.

**Comment by zluca** [comment]
> как на хабре

На харбе картинок в комментах нету. =) Сам то текст конечно можно сделать как на хабре, а вот как быть с картинками? А то напостят клопоты.
Для себя использую вот такой стиль:

```
.comment-bad{min-height:12px;}
.comment-bad>.comment-info{padding-bottom:0;}
.comment-bad>.folding{top:0;}
.comment-bad>.comment-content{display:none;}
.comment-bad:hover>.comment-content{display:block;}
.comment-bad:hover>.folding{top:8px;}
```

У плохих комментов видны только заголовки, пока мышкой на них не наведёшь. Выглядит вот так:
<img src="https://cdn.everypony.ru/storage/02/43/83/2016/09/14/d98cf585f9.png" />

Как на Хабре сделать гораздо проще, всего в 2 правила, вот так:

```
.comment-bad .text{color:#ccc;}
.comment-bad:hover .text{color:inherit;}
```

<img src="https://cdn.everypony.ru/storage/02/43/83/2016/09/14/27789d2703.png" />

Но это нормально работает пока коммент чисто текстовый. @Orhideous в общем что пилить? =)

**Comment by roman901** [comment]
Поиграйся с opacity, чтоль

**Comment by undertroll** [comment]
Тогда нужно скрытие картинок в любом случае. Защита от мудаков.

**Comment by zluca** [comment]
> Поиграйся с opacity, чтоль

Спасибо, опасити внезапно работает. =) 
Выглядит с картинками вот так:
<img src="https://cdn.everypony.ru/storage/02/43/83/2016/09/14/201b03f92d.png" />

Если больше указаний от начальства не поступит впилю завтра такой коммит:
```
.comment-bad .text{
    opacity:0.4;
}
.comment-bad:hover .text{
    opacity:inherit;
}
```

**Comment by roman901** [comment]
0.3 и впушивай :)

**Comment by zluca** [comment]
Завтра, а то я вечно тороплюсь, а потом переделываю. :D

**Comment by undertroll** [comment]
Так, ждать указаний от начальства (хотя начальство я тут тоже все же немного...) и да, скрытие картинок ОБЯЗАТЕЛЬНО. Забыли про набеги дебилов? АБК живо напомнит что к чему.

**Comment by roman901** [comment]
@undertroll не вижу смысла, если честно - если все ок, то все ок, а если плохо - всегда можно сделать revert

**Comment by zluca** [comment]
Комбинированный вариант:
```
.comment-bad .text img{
    opacity:0;
}
.comment-bad .text{
    color:#ccc;
}
.comment-bad:hover .text{
    color:inherit;
}
.comment-bad:hover .text img{
    opacity:inherit;
}
```
Текст затеняем, рисунки полностью убираем. По наведении мышки всё видно как обычно.

**Comment by undertroll** [comment]
Так сойдет, если пихчи нах удаляются.

**Comment by zluca** [comment]
> если пихчи нах удаляются. 

Они не будут видны пока не навести на них мышкой. Это специально чтобы можно было посмотреть и самому уже решать минусовать или нет.

**Comment by Orhideous** [comment]
Годно. Можно коммитить (и, естественно, не забыть о том, что у нас всё в [Stylus](http://stylus-lang.com/), но там несложно, код переносится почти 1:1). А, и да: https://help.github.com/articles/closing-issues-via-commit-messages/

**Comment by zluca** [comment]
Оки-доки-локи! Пошёл комитить.

**Comment by zluca** [comment]
Обнаружил неприятный эффект в процессе эксплуатации - ссылки просвечивают.
<img src="https://cdn.everypony.ru/storage/02/43/83/2016/09/22/0b3acc5317.png" />
Тоже самое с ифреймами. Ща запилю фикс на хотфикс. :D
