### ISSUE TITLE
Добавить страницы FAQ и справки редактора и ссылки на них

### ISSUE THREAD

**Issue by undertroll** [everypony/tabun#44]
Для последующего изменения в соответствии с актуальными данными.

**Comment by Orhideous** [comment]
Будет сделано после #14

**Comment by Orhideous** [comment]
Сделано в 1847f135d7ac3891fe4538eac5af30bf704218f2, фикстуры в [`fixtures/pages.sql`](https://github.com/everypony/tabun/blob/development/fixtures/pages.sql) — там вместо TODO можно писать любой валидный HTML. На продакшене там будет реальный FAQ и реальные правила, но локально посмотреть работоспособность и/или верстку хватит.

**Comment by zluca** [comment]
`  (1, null, 'faq', 'faq', 'FAQ', 'TODO', '2016-09-13 22:26:46', null, '', '', 1, 1, 1, 0),
(2, null, 'rules', 'rules', 'Правила', 'TODO', '2016-09-13 22:26:46', null, null, null, 1, 1, 2, 0)`

Ещё надо добавить "Справочник по редактору".

> На продакшене там будет реальный FAQ и реальные правила

Их ещё переписать надо. Можно здесь где-нибудь хтмл файлики создать для совместного редактирования?

**Comment by Orhideous** [comment]
Старый FAQ я вытащу, да.

**Comment by zluca** [comment]
@Orhideous 

> можно писать любой валидный HTML

А инлайн скрипты и стили нормально зайдут?

**Comment by Orhideous** [comment]
> любой валидный HTML
