### ISSUE TITLE
Интегрировать цитатник

### ISSUE THREAD

**Issue by zluca** [everypony/tabun#45]
### Проблема
Он не работает.

### Решение
Поднять и интегрировать цитатник с [everypony/twicher](https://github.com/everypony/twicher)

**Comment by undertroll** [comment]
В процессе починки. Точнее, уже сделано.

**Comment by zluca** [comment]
> Точнее, уже сделано. 

Ок, тогда закрою.

**Comment by zluca** [comment]
Как я понимаю к дедлайну не успеваем. Там может убрать с сайдбара блок "Разум Табуна" до лучших времён?

**Comment by undertroll** [comment]
Отставить панику, все успеваем.

**Comment by Orhideous** [comment]
Я буду делать в ветке [tabun/twicher](/everypony/tabun/tree/twicher)
