### ISSUE TITLE
Удалить кнопку "Тэги"

### ISSUE THREAD

**Issue by zluca** [everypony/tabun#46]
### Проблема
По ссылке tabun.everypony.ru/tags/ выдаёт ошибку 404.
### Что делать?
Варианты:
1. Удалить кнопку.
2. Переделать ссылку на рабочую, например tabun.everypony.ru/tag/pony/
3. Сделать всё как было.
4. Сделать как-нибудь по новому.

**Comment by roman901** [comment]
5. Сделать.

**Comment by Orhideous** [comment]
@roman901 Кстати, по тегам строится индекс ElasticSearch?

**Comment by roman901** [comment]
Естестно

**Comment by Orhideous** [comment]
@undertroll Смотри, вернуть эту страницу можно, но _надо ли_ кому-то список всех тегов?

**Comment by undertroll** [comment]
@Orhideous Если там не облако тегов, то едва ли. 
А если даже и облако, где выделены самые частые, то это не самая приоритетная вещь и пока что нафиг не нужна, есть намного более актуальные вещи.

**Comment by Orhideous** [comment]
Будет решено в #48

**Comment by zluca** [comment]
Если просто удалить будет вот так:
<img src="https://cdn.everypony.ru/storage/02/43/83/2016/09/19/f6acecaead.png" />
По моему не очень красиво.
Можно добавить на место тэгов другую кнопку - например "Правила". Или сделать кнопку Смайлопак на всю ширину и картинкой как "На пони"

**Comment by roman901** [comment]
Можно просто смайлопак наверх убрать, к правилам и факу :)

**Comment by roman901** [comment]
@Orhideous удалять саму кнопку можно сейчас, там же ActionTags, а не ActionTag. Разный функционал

**Comment by zluca** [comment]
> Можно просто смайлопак наверх убрать, к правилам и факу :)

Хедер и так перегружен. Мне вот так больше нравиться:
<img src="https://cdn.everypony.ru/storage/02/43/83/2016/09/19/1888f95675.png" />

**Comment by Orhideous** [comment]
@zluca отлично :) Сделаешь?
_P.S._ Небольшая просьба: если будешь делать коммиты, пиши в нем более детальное описание, не просто «this fixes #…»; это помогает при быстром просмотре истории понять, что вообще было сделано в коммите. Вот [тут](http://chris.beams.io/posts/git-commit/) написано подробнее.

**Comment by zluca** [comment]
> Сделаешь?

Сделаю. Только какие ссылки прописывать для привил и фака? 

> пиши в нем более детальное описание

Ок, постараюсь. =)

**Comment by zluca** [comment]
В header_top.tpl вот так сделано:
```
         <li>
            <a href="{router page='page'}faq/">{t}faq{/t}</a>
        </li>
        <li>
            <a href="{router page='page'}rules/">{t}rules{/t}</a>
        </li>
```

Это правильный ссылки? И из хедера их перенести или оставить чтоб 2 раза было?

**Comment by zluca** [comment]
> Из хедера ссылки удалить или оставить чтоб 2 раза было?

Вообще глупость конечно сморозил. Зачем 2 раза одинаковые ссылки почти что рядом. =)
