### ISSUE TITLE
Реализовать переход к поиску при нажатии на тег

### ISSUE THREAD

**Issue by roman901** [everypony/tabun#48]
Сейчас при нажатии на тег выводится страница /tag/<name>. Не вижу смысла оставлять ее, если новый поиск (#1) поддерживает поиск по тегам. Можно сделать флаг поиска только по ним и переадресовывать туды.

**Comment by zluca** [comment]
> Можно сделать флаг поиска только по ним и переадресовывать туды.

Например вот так я делал в своём скрипте - переключатели типов поиска.
<img src="https://cdn.everypony.ru/storage/02/43/83/2016/09/18/3c2a4574a7.png" />

**Comment by Orhideous** [comment]
Да, всё верно: лучше сделать поиск по тегам разновидностью способов поиска контента.
