### ISSUE TITLE
Лесенка комментариев

### ISSUE THREAD

**Issue by zluca** [everypony/tabun#50]
### Проблема
В комментариях при большой глубине вложенности возникает неприятная ситуация, когда текст комментария скукоживается до неприличной ширины. &darr; Картинка &darr;
<img src="https://cdn.everypony.ru/storage/02/43/83/2016/09/21/6be6d2ad6c.png" />
### Причина
Элемент #content-wrapper внутри которого размещаются комментарии и сам топик- float. Повлиять на ширину вышележащих элементов он не может (потому что float).
Снаружи #container с шириной от 950px до 1600px.
Внутри лестница комментариев глубиной 60 и с отступом 16px. 60х16=960px.
То есть получается на маленьких экранах сверху #container ограничивает размер в вайдмоде 950, а снизу у комментариев отступ 960. Естественно ничего хорошего из этого не выйдет.
### Что делать?
Наилучший вариант - уменьшить максимальную глубину вложенности до 40-50 и отступ комментария до 12-14.
Тогда получим - 40х14=560px или 50х12=600px. Т.е. по крайней мере в вайдмоде будет не менее 300 пикселей на сам каммент.

_зы если трогать comment.max_tree по каким-то причинам трогать нельзя есть ещё пару идей, но там сильно заморачиваться надо. =)_

**Comment by Orhideous** [comment]
`comment.max_tree` влияет только на отображение. Дай, пожалуйста, скрин, как это всё выглядит на новой глубине вложенности и стилях?

**Comment by zluca** [comment]
[Вот](https://cdn.everypony.ru/storage/02/43/83/2016/09/21/24135d0496.png). Отступы 14px глубина 40 (два нижних коммента уже на макс глубине). #container я принудительно на 950px выставил чтобы сымитировать худший вариант.

**Comment by Orhideous** [comment]
Отлично.

**Comment by zluca** [comment]
Оки, щас сделаю. =)
