### ISSUE TITLE
Смайлики Юникода обрезают комментарии

### ISSUE THREAD

**Issue by undertroll** [everypony/tabun#54]
В данном конкретном случае - смайлик (U+1F605)
**Что произошло:**
Был написан [комментарий](https://tabun.everypony.ru/blog/draw_help/140937.html#comment10140498) с мобильника, в тексте был использован вышеуказанный смайлик.
**Результат:**
Комментарий запостился строго до смайлика. Вся часть после была утеряна. Причём на почту пришло полное, не обрезанное, уведомление. 

Проблема в MySQL.

**Comment by zluca** [comment]
Basic Unicode (U+0000 to U+FFFF) работает нормально, всё что выше глючит.
Причём в предпросмотре все символы отображаются.

Можно замутить костыль со стороны клиента, чтобы проблемные символы вырезал.

**Comment by zluca** [comment]
Дополнение. Обрезают не только комментарии, но и вообще всё. Заголовоки [топиков](https://tabun.everypony.ru/blog/fanart/162567.html), текст топиков, тэги.
<img src="https://cdn.everypony.ru/storage/02/43/83/2016/10/07/f65132e939.png" />

**Comment by undertroll** [comment]
@zluca сделаешь костыль этот? Едва ли стоит тратить усилия и решать это полноценно.

**Comment by zluca** [comment]
@undertroll там пару строчек говнокода добавить. =) Можно ближе к релизу 1.4 если никто нормально не сделает к тому времени.

**Comment by undertroll** [comment]
@zluca не сделает. Некому. Есть понужнее задачи, вон, куча issues. Пили свой говнокод. Ставлю assignment на тебя и майлстоун.

**Comment by zluca** [comment]
Костыль работает только с комментариями. К топикам его так просто не прикрутить. Там вообще скрипта на отдачу нету, вместо этого используется отправка формы.
