### ISSUE TITLE
footer

### ISSUE THREAD

**Issue by zluca** [everypony/tabun#57]
Футер в нынешнем виде это на мой вкус бестолковое нагромождение блоков.
<img src="https://cdn.everypony.ru/storage/02/43/83/2016/09/23/6efab96d86.png" />

Руки чешутся переделать. Вот как я это вижу.

> Вариант 1 светлая тема:

<img src="https://cdn.everypony.ru/storage/02/43/83/2016/09/23/15cd2a1d2c.png" />
<hr>

> тёмная тема:

<img src="https://cdn.everypony.ru/storage/02/43/83/2016/09/23/b29f0930fa.png" />
<hr>

> без фона:

<img src="https://cdn.everypony.ru/storage/02/43/83/2016/09/24/e40845d792.png" />
<hr>
голосуйте, подписывайтесь, ставьте лайки!

**Comment by roman901** [comment]
Выровнять право и лево по высоте и так хорошо будет.

**Comment by zluca** [comment]
Т.е. дырка из которой торчит заливка боди тебя не смущает? Меня вот прям бесит, неряшливо смотриться, Рарити бы не одобрила такое. =) 
Конечно если выровнять высоту уже лучше смотрится, но не идеально:
<img src="https://cdn.everypony.ru/storage/02/43/83/2016/09/24/53f904b62d.png" />

**Comment by roman901** [comment]
Ну так это, убери дырку просто :)

**Comment by zluca** [comment]
Ок, добавил 3 вариант без фона, подождём кого-нить из начальства. =)

**Comment by roman901** [comment]
Начальства ждать - умереть быстрее.
@Orhideous ау, вы где?

**Comment by undertroll** [comment]
@zluca @roman901 
Будем считать, что за отсутствием главного начальства бразды правления переходят к малому начальству.
Запиливайте темную тему, смотрится хорошо.

**Comment by roman901** [comment]
@undertroll <sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup>я согласен работать только на Орхида!</sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub>

**Comment by roman901** [comment]
@zluca у меня всё стремно выглядит.

**Comment by zluca** [comment]
А ты все 3 коммита дождался? Я ж прямо через сайт редактирую. =)

**Comment by roman901** [comment]
А, третий пришел позже того как закрылась ишшуя :)
