### ISSUE TITLE
Лента активности отдельного пользователя не отображается в профиле

### ISSUE THREAD

**Issue by zluca** [everypony/tabun#59]
Просматривая исходники обнаружил страшное - оказывается на Табуне можно смотреть активность отдельного пользователя, достаточно в профиле дописать /stream в адресной строке.

Собственно вопрос. @Начальство это специально спрятали? Если нет то предлагаю добавить пункт в менюшку:
<img src="https://cdn.everypony.ru/storage/02/43/83/2016/09/26/9cb2b2b9cf.png" />

Кроме того там надо кнопку пофиксить по аналогии с #22.

**Comment by undertroll** [comment]
Нет, оставить как есть, не надо двоить. За отдельным пользователем и в активности следить можно, есть поле "Люди".

**Comment by zluca** [comment]
А чё там усложнится то? =) Сам функционал уже есть (и я подозреваю был с начала Табуна). Просто не было внятной ссылки на него. Получается секретная фишка для посвящённых.

В любом случае пофиксил кнопку "Получить ещё события".

**Comment by roman901** [comment]
Плюсую, фича крутая. Не вижу никаких причин её не использовать.

**Comment by undertroll** [comment]
@zluca @roman901 Ок, подойдем с другой стороны. Будут ли её реально использовать, кто и с какой целью.

**Comment by zluca** [comment]
> кто

Те же кто и сейчас Активность юзает.
>с какой целью

Чтобы посмотреть активность отдельного юзера. Когда подписываешься на несколько десятков человек выделить действия одного проблема. А ото всех отписываться чтобы потом по новой подписываться тот ещё квест. =)

**Comment by Orhideous** [comment]
Давайте так. Если функционал есть, то и кнопку покажем. А там подправим, если что.

**Comment by undertroll** [comment]
@Orhideous Ну, ладно. Можно пока что впилить. Благо выпилить недолго.

**Comment by Orhideous** [comment]
Дело в том, что это лишь шорткат к основной ленте, так что…
