### ISSUE TITLE
Шаблоны комментариев

### ISSUE THREAD

**Issue by zluca** [everypony/tabun#63]
Почитал тут в исходниках как генерируются комменты на Табуне и честно говоря офигел. Дико переусложнённый [comment.tpl](https://github.com/everypony/tabun/blob/development/templates/skin/synio/comment.tpl) с кучей ифов на все случаи жизни.

Например проверка на админа делается 3 раза, проверка на то что пользователь не аноним 4 раза - т.е. если мы рисуем дерево из 1000 комментов будем делать 3000 проверок на админа, 4000 на логин + проверка на почту 1000 раз и ещё по мелочи разной ерунды. Мне так кажется что именно из-за этого йиффа тормозят большие топики и не работает эпичный тред СашиФлаера.

**Что делать?**

Вынести все проверки на админство, логин и прочие вверх по иерархии в [comment_tree.tpl](https://github.com/everypony/tabun/blob/development/templates/skin/synio/comment_tree.tpl) до входа в цикл, чтобы не делать дурную работу. Создать мелкие, но быстрые темплейты комментариев отдельно для админов, юзеров, анонимов и т.д. с минимумом ифов.

Хотя может я просто нуп и не шарю. @Orhideous надо твоё экспертное мнение. =)

ЗЫ ещё обнаружил такой косяк. Для удаления комментов по рейтингу используется module.user.bad_rating - тот же параметр что и для деактивации пользователей. Сейчас цифры совпадают - юзеры отключаются при карме меньше -10 и комменты удаляются при рейтинге меньше -10, но вообще это кривейший костыль, надо делать раздельно.

**Comment by roman901** [comment]
Комменты и топики по-хорошему бы вообще переписать, правда - начиная от отображения, заканчивая логикой в бд. Одно только переделывание отображения даст прирост в скорости

**Comment by zluca** [comment]
Ну если переписывать. Была у меня тут идея. comment_tree выкинуть совсем, отдавать клиенту топик без комментов, а потом ажаксом подгружать и дерево со стороны клиента строить. Во-первых меньше нагрузка на сервер, во-вторых можно почитать сам топик пока комменты грузятся.

**Comment by undertroll** [comment]
>во-вторых можно почитать сам топик пока комменты грузятся.
Издеваться изволите? "Нахуй, нахуй" -- кричали бояре.

Многие часто только из-за комментов и заходят. У нас не ЖЖ все же.

**Comment by zluca** [comment]
@undertroll ты не врубился о чём я. 
Сейчас при заходе в длиннопост 20-30 секунд пялишься в белый экран. А будет так - через секунду виден сам топик, через 10-15 комменты.

**Comment by undertroll** [comment]
@zluca 
Сроду не пялился в белый экран. Достаточно быстро все открывает.

**Comment by zluca** [comment]
Значит ты под Хромом сидишь. =) А вот попробуй в Файрфоксе открыть топик на 3-4 тыщщи комментов.

**Comment by undertroll** [comment]
@zluca Такие встречаются исключительно редко. Если в результате изменения будут комменты во **всех** топиках подгружаться через секунд 15, то едва ли такое нужно.

**Comment by zluca** [comment]
Не во всех конечно, только в эпичнотредах.

В любом случае без Орхидова одобрения ничего трогать не буду, так что можешь не кипешевать. :D

**Comment by roman901** [comment]
Ну вы чего, а? Есть проверенное решение - первые N комментов в шаблон, остальное ajax

**Comment by roman901** [comment]
N может быть и сотней.

**Comment by zluca** [comment]
А не упростить ли сам ХТМЛ комментария подумал я? Сейчас коммент состоит минимум из 29 элементов и это очень много. Если, скажем, в топике 1000 комментов выходит 29000 элементов в ДОМе минимум (а на самом деле гораздо больше). Вот оно и тормозит нещадно. Выглядит ХТМЛ примерно вот так:

```
<section data-id="" id="comment_id_" class="comment ">
    <a name="comment"></a>
    <div data-id="" class="folding"></div>
    <div id="comment_content_id_" class="comment-content">
        <div class="text current"></div>
    </div>
    <ul class="comment-info">
        <li class="comment-author comment-topic-author" title="Автор">
            <a href="">
                <img src="" class="comment-avatar">
            </a>
            <a href=""></a>
        </li>
        <li class="comment-date">
            <time datetime="" title=""></time>
        </li>
        <li id="vote_area_comment_" class="vote">
            <div class="vote-up" onclick=""></div>
            <span class="vote-count" id="vote_total_comment_">0</span>
            <div class="vote-down" onclick=""></div>
        </li>
        <li class="comment-favourite">
            <div onclick="" class="favourite ">В избранное</div>
            <span class="favourite-count" id="fav_count_comment_" hidden=""></span>
        </li>
        <li class="comment-link">
            <a href="#comment" title="Ссылка на комментарий">
                <i class="icon-synio-link"></i>
            </a>
        </li>
        <li class="goto goto-comment-parent">
            <a href="" onclick="" title="Ответ на">↑</a>
        </li>
        <li class="goto goto-comment-child">
            <a href="#" title="Обратно к ответу">↓</a>
        </li>
        <li>
            <a href="#" onclick="" class="reply-link link-dotted">Ответить</a>
        </li>
        <li class="modify-notice"></li>
    </ul>
</section>
```
Много лишних вложений + ссылка `<a name="comment"></a>` не понятно к чему вообще. Элемент `<li class="modify-notice"></li>` проставляется в каждый коммент независимо от того редактировался он или нет. @Farxial - это в твой огород камушек.
Если поубирать вложения можно сделать вот так:
```
<section data-id="" id="comment_id_" class="comment ">
    <div data-id="" class="folding"></div>
    <div id="comment_content_id_" class="comment-content text current"></div>
    <div class="comment-info">
        <img src="" class="comment-avatar">
        <a class="author" href=""></a>
        <time datetime="" title=""></time>
        <div id="vote_area_comment_" class="vote">
            <div class="vote-up" onclick=""></div>
            <span class="vote-count" id="vote_total_comment_">0</span>
            <div class="vote-down" onclick=""></div>
        </div>
        <div onclick="" class="favourite ">В избранное</div>
        <span class="favourite-count" id="fav_count_comment_" hidden=""></span>
        <a class="comment-link" href="#comment" title="Ссылка на комментарий"></a>
        <a class="goto goto-comment-parent" href="" onclick="" title="Ответ на">↑</a>
        <a href="#" onclick="" class="reply-link link-dotted">Ответить</a>
    </div>
</section>
```
Остаётся 16 элементов - почти в 2 раза меньше. Но это не предел. Вообще все управляющие элементы: фолдинги, стрелочки, ссылочки можно генерировать на лету со стороны клиента по запросу - по наведению мыши или тыку пальцем для мобилок. Останется всего 8 элементов! ХТМЛ будет вот такой:
```
<section data-id="" id="comment_id_" class="comment ">
    <div id="comment_content_id_" class="comment-content text current"></div>
    <div class="comment-info">
        <img src="" class="comment-avatar">
        <a class="author" href=""></a>
        <time datetime="" title=""></time>
        <div id="vote_area_comment_" class="vote">
            <span class="vote-count" id="vote_total_comment_">0</span>
        </div>
    </div>
</section>
```
Выглядеть будет как то так:
<img src="https://cdn.everypony.ru/storage/02/43/83/2016/11/03/1bae0aa8d7.png" />
Сразу непривычно, но по моему даже интреснее, меньше отвлекающих мелких деталей. Можно поставить юзерстиль чтобы пощупать прямо на Табуне:
```
  .folding,.comment-favourite,.comment-link,.goto,.reply-link,.comment-edit-bw,.comment-info .vote-down,.comment-info .vote-up{
    opacity: 0;
    transition: opacity .3s;
  }
  section:hover li, section:hover .reply-link, section:hover .vote div, section:hover .folding{
    opacity: 1;
  }
  .comment-current li, .comment-current .reply-link, .comment-current .vote div, .comment-current .folding{
    opacity: 1;
  } 
```
ЗЫ как вам такая идея?
ЗЗЫ естественно стили тоже придётся переделать, да и скрипты местами отвалятся.
ЗЗЗЫ вообще идею я подсмотрел у андреймала, только у него элементы стилями убираются. Мой же замысел вообще их генерировать со стороны клиента.

**Comment by Farxial** [comment]
> Элемент `<li class="modify-notice"></li>` проставляется в каждый коммент независимо от того редактировался он или нет. @Farxial - это в твой огород камушек.

Я сделал так потому что в _таком_ DOM хуже уже не будет.
— Нужно переделать?

----------
Идея здравая, так что, если ты готов на это (в т.ч. на оптимизацию для поддержки современными поисковиками — они, увы, пока не придумали ничего лучше чем требовать HTML)...

**Comment by zluca** [comment]
> Нужно переделать?

Надо бы для начала чтобы @Orhideous решил насколько радикально резать. А вдруг вообще не разрешит? =)
> оптимизацию для поддержки современными поисковиками

Элементы управления комментами (стрелочки, ссылочки и это вот всё) не должны поисковики интересовать, так что не вижу проблемы.

**Comment by zluca** [comment]
Вроде все глюки выловил. Закрываю.
