### ISSUE TITLE
Проблема с добавлением в "Избранное"

### ISSUE THREAD

**Issue by zluca** [everypony/tabun#65]
### Проблема №1
Взято с [битбакет](https://bitbucket.org/Orhideous/tabun/issues/43/------------------------------------------)
При добавлении поста в Избранное пропадает счётчик.

### Причина
ХТМЛ структура не соответствует ожиданиям скрипта.

### Решение
Переделать темплейт футера топика.

### Проблема №2
@Orhideous вот в [этом](https://github.com/everypony/tabun/commit/0cee7f349bc55b4e2e8d8e383f5ac58cdedc8e62#diff-6728918b470628a7b3f7eeb4117a3bcd) коммите в файле [favourite.coffee]( https://github.com/everypony/tabun/blob/development/frontend/scripts/app/favourite.coffee) ты в объекте favTargets выкинул 'talk' и добавил 'user'. В результате чего не работает добавление в "Избранное" переписок в "Сообщениях".

### Решение
Позвать Орхи. 
Я пока править не буду, посмотри сам, а то может я не понял хитрый план. =)

**Comment by zluca** [comment]
>  Orhideous modified the milestone

Там одну строчку поправить. Я б и сам сделал, но боюсь не понял твоей задумки в упомянутом коммите поэтому и не трогаю.

**Comment by Orhideous** [comment]
@zluca Если успеешь до вечера, то сделай, пожалуйста. Я думал уже релиз формировать.

**Comment by zluca** [comment]
Заметка на будущее: "Выпытать у Орхидеуса нафига он добавлял user как валидную цель для favourites". :D
