### ISSUE TITLE
Не проставляется класс .comment-topic-author

### ISSUE THREAD

**Issue by zluca** [everypony/tabun#66]
### Проблема

Взято с [битбакета](https://bitbucket.org/Orhideous/tabun/issues/224/comment-topic-author)
Не присваивается класс .comment-topic-author комментариям автора поста.
1. При подгрузке новых комментариев ажаксом
2. в переписке в "Сообщениях"
3. в списке комментариев в профиле. 
### Исследование проблемы

В темплейте [comment.tpl](https://github.com/everypony/tabun/blob/development/templates/skin/synio/comment.tpl) за назначение этого класса отвечают 2 переменные: $iAuthorId, $sAuthorNotice. Если их не назначить соответственно ничего не работает. В файле [topic.tpl](https://github.com/everypony/tabun/blob/development/templates/skin/synio/actions/ActionBlog/topic.tpl) они назначены как положено, поэтому при заходе в топик изначально всё правильно отображается.

2) Пофиксить "Сообщения" проще всего. Нужно в [read.tpl](https://github.com/everypony/tabun/blob/development/templates/skin/synio/actions/ActionTalk/read.tpl) скопипастить:

```
    iAuthorId=$oTopic->getUserId()
    sAuthorNotice=$aLang.topic_author
```

где-нибудь между 44и45 строками. Это я бы мог сделать и сам, но не уверен 100% что это баг, а не фича.

1) Ажакс запрос обрабатывается тут &rarr; [Comment.class.php](https://github.com/everypony/tabun/blob/development/classes/modules/comment/Comment.class.php) в функции GetCommentsNewByTargetId. Насколько я понимаю там внутри $oViewerLocal и надо объявить искомые переменные. Но тут уже без знания пхп не обойтись ctrl+C ctrl+V не сработает, так что @ктотутшаритвphp посмотрите сами если время будет.

3) Список комментариев в профиле не использует тепмлейт комментс.тпл. Там в принципе тоже можно переделать по аналогии, если это вообще необходимо?

**Comment by lunavod** [comment]
Не проверял, но вроде должно быть как-то так:
```
$oViewerLocal->Assign('iAuthorId', $oComment->getTarget()->getUserId());
$oViewerLocal->Assign('sAuthorNotice', $aLang.topic_author);
```
Где-то после 649 и до 655.

**Comment by zluca** [comment]
Попробовал код Лунавода, посмотрим заработает ли на транке. Единственное что oComment нельзя использовать до объявления, переделал немного.

**Comment by zluca** [comment]
```
Copy configuration from /tmp/tmp.b1JiZ2lC6N to server
ECDSA host key for IP address '176.103.50.28' not in list of known hosts.
tmp.b1JiZ2lC6N                                100%  523     0.5KB/s   00:00    
Switch to new config
ECDSA host key for IP address '176.103.50.28' not in list of known hosts.
ERROR:lithos_check: Can't read child config "php": Error opening config /mnt/ssd/images/tabun-trunk/php-trunk.3e028ac1/lithos/php.yaml: No such file or directory (os error 2).
Sometimes the reason of reading configuration is absolute symlinks for config, in that case it may work in real daemon, but better fix it.
Fatal error: Configuration check failed with exit status: exit code: 1
Connection to internal.everypony.ru closed.
Script failed with status 1
failed to deploy
```

@Orhideous

**Comment by Orhideous** [comment]
@zluca fix'd

**Comment by zluca** [comment]
Так в почте класс проставляется. А вот в ажаксе пришлось откатить, так как всё поломалось. Насколько я понимаю $sId - это номер топика и вот из него надо извлекать ИдЮзера как-то.

**Comment by zluca** [comment]
В общем так никто из пыхапистов не горит желанием фиксить забабахал костыль на жсе. =)
