### ISSUE TITLE
Форма "О себе" на странице "Настойки"

### ISSUE THREAD

**Issue by zluca** [everypony/tabun#70]
### Проблема
[битбакет](https://bitbucket.org/Orhideous/tabun/issues/149/)

При заполнении формы если превысить лимит символов она не только не сохраняется, но и удаляется старое значение. То же самое касается поля "Имя".
### Решение
Со стороны клиента:
- Добавить атрибут maxlength к элементам input i textarea
- (???) оснастить УИ явной информацией об ограничении. Например:
<img src="https://cdn.everypony.ru/storage/02/43/83/2016/10/05/a9107f1cfd.png" />
Со стороны сервера:
- вынести ограничение в конфиг
- (???) увеличить ограничение, не маловато ли 3000?
- при инвалидации не удалять старое значение

**Comment by lunavod** [comment]
И маркитап добавить надо.

**Comment by zluca** [comment]
Ну вообще да, надо. Но я пока реалистичные цели ставлю чтобы к следующему релизу успеть.

**Comment by lunavod** [comment]
Его разве сложно привязать?

**Comment by zluca** [comment]
Может и не сложно, но эт разбираться надо. Я и так себе много работы напридумывал. =)
Если есть желание сделать - возьми и сделай.
