### ISSUE TITLE
Адаптивный дизайн для Табуна

### ISSUE THREAD

**Issue by zluca** [everypony/tabun#71]
### Проблема

[битбакет](https://bitbucket.org/Orhideous/tabun/issues/226/viewport)
Адаптивный дизайн отсутствует.
### Решение

Запилить адаптивный дизайн.

**Comment by roman901** [comment]
Не вижу никаких проблем в данном случае, тег правильно указывает viewport

**Comment by zluca** [comment]
Там по ссылке(которая умерла) Veon жаловался что у него что-то не так масштабируется.

**Comment by zluca** [comment]
@undertroll можешь сюда текст с картинкой скопировать? А то незареганым не видно.

**Comment by zluca** [comment]
Провёл такой эксперимент - сохранил Главную Табуна локально и посмотрел её через Оперу в режиме разработчика (там есть эмуляция мобилки).

С вьюпортом:
[вертикально](http://storage3.static.itmages.ru/i/16/1006/h_1475753796_7848666_6be522fd94.png)
[горизонтально](http://storage1.static.itmages.ru/i/16/1006/h_1475753778_2154617_15dc05443a.png)

Без вьюпорта:
[вертикально](http://storage6.static.itmages.ru/i/16/1006/h_1475753799_5035790_893103f63e.png)
[горизонтально](http://storage4.static.itmages.ru/i/16/1006/h_1475753797_3154998_eab40f706b.png)

Т.е. он по сути масштабирует страницу, хотя написано "initial-scale=1.0". Без него мне кажется лучше выглядит. А масштаб юзер сам должен подстраивать под свои вкусы. 

Ещё одно отличие - без вьюпорта панелька вайдмода сразу видна, а с ним только когда начинаешь вниз листать.

**Comment by zluca** [comment]
Продолжаю мучать виртуальный Айфон =) Попробовал вот такой ксс:
```
    @media only screen and (orientation: portrait) {
		body.widemode #content-wrapper {
 		        width: 70%!important;
		}
		#content-wrapper {
    			float: left;
    			width: 100%!important;
		}
		body.widemode #sidebar {
    			float: right;
    			position: relative;
    			width: 25%;
    			display: inline-block!important;		
		}
		#sidebar {
			display: none!important;
		}
    }
```

Т.е. в портретном режиме широкий режим по умолчанию. При повороте обратно выставляется нормальный.

Скриншотики.
С вьюпортом:
[вертикально](http://storage9.static.itmages.ru/i/16/1012/h_1476306442_1033737_538e5e200d.png)
[горизонтально](http://storage8.static.itmages.ru/i/16/1012/h_1476306430_7311473_170cb30682.png)

Без вьюпорта:
[вертикально](http://storage1.static.itmages.ru/i/16/1012/h_1476306442_7338104_9f0a141526.png)
[горизонтально](http://storage2.static.itmages.ru/i/16/1012/h_1476306444_8533304_cddc5e2969.png)

**Comment by zluca** [comment]
В общем пришёл к выводу что надо пилить адаптивный дизайн. На выходных попробую что-нибудь эдакое изобразить.

**Comment by roman901** [comment]
Я подключусь, так то. Тоже есть мысли

**Comment by zluca** [comment]
Итак как и обещал показываю черновую версию.
Работает следующим образом:
1025+ - оставляем всё как есть по возможности
769-1024 - ужимаем паддинги-шмаддинги, но в целом всё тоже самое.
568-768 - вайд-мод по дефолту, боковая панелька наезжает на контент не сдвигая его.   Глубина лесенки комментов - 20.
Скрины:
[основа](http://storage6.static.itmages.ru/i/16/1015/h_1476562791_3301329_33900c6c28.png)
[боковая панель](http://storage6.static.itmages.ru/i/16/1015/h_1476562791_5101251_36964846a7.png)
[комментарии](http://storage4.static.itmages.ru/i/16/1015/h_1476562788_7899649_753630588d.png)
менее 568 - полное разделение на 2 экрана, переключение через кнопку вайдмода. Тулбар приклеен внизу. Максимальная глубина лесенки - 5.
Скрины:
[Основа](http://storage1.static.itmages.ru/i/16/1015/h_1476562799_7511067_f459b67853.png)
[второй экран](http://storage1.static.itmages.ru/i/16/1015/h_1476562798_8513960_70b0eee870.png)
[комментарии](http://storage7.static.itmages.ru/i/16/1015/h_1476562795_1737072_a2d75b5a5c.png)

**Comment by Orhideous** [comment]
@zluca Неверноятно :) Как работает боковая панель на сенсорных устройствах?

**Comment by zluca** [comment]
@Orhideous Да фиг знает. Я из под эмулятора в Файрфоксе смотрю. Моя старенькая Нокия только в Оперу-мини умеет. =)
Надо что бы кто-то с живой мобилки потестил.

**Comment by Orhideous** [comment]
Давай в понедельник. Я на работе пойду в отдел тестирования, там есть любые устройства.
Напиши, в целом, что надо протестить и на каких устройствах (примерно).

**Comment by Orhideous** [comment]
Или тебе срочно?

**Comment by roman901** [comment]
Могу завтра вечером проверить на своей микротестовой ферме

**Comment by zluca** [comment]
Да нет, не срочно. 1.4 то ещё не скоро. Да и тут работы ещё валом, найду чем заняться.
Я просто не уверен как оно на живых устройствах выглядит и не врёт ли эмулятор.

**Comment by Orhideous** [comment]
@zluca У меня, увы, только HTC Desire C есть, как пример очень маленького экрана.

**Comment by zluca** [comment]
@roman901 проверь если не трудно.
@Orhideous И это. Я там флексбоксов везде налепил, потому-что без них очень уж тяжко. Интересно как они себя на всяких отсталых браузерах поведут.

**Comment by zluca** [comment]
А как вам такое оформление заголовков топиков?
<img src="https://cdn.everypony.ru/storage/02/43/83/2016/10/16/c20657baf0.png" />

**Comment by Orhideous** [comment]
Вполне, если в топике есть хоть одна картинка. А если ее нет?

**Comment by zluca** [comment]
Это ж аватарка. Аватарка всегда есть даже у анонов. :)

**Comment by Orhideous** [comment]
А, я думал, это изображение из темы.

**Comment by AJFly** [comment]
Тестить еще надо? Могу на айфоне..

**Comment by zluca** [comment]
@AJFly Оно то нужно. Но на транке дев ветка отображается, так что до мержа не потестишь. Если конечно не умеешь ваггу запускать.

**Comment by roman901** [comment]
@zluka а ты ваггу запускешь?

**Comment by zluca** [comment]
@roman901 Не. Я только статику компилирую и прям в браузере подменяю.

**Comment by AJFly** [comment]
@zluca 
> Если конечно не умеешь ваггу запускать.

Ээ... Вряд ли.

**Comment by Orhideous** [comment]
@zluca Если код особо ничего не ломает, то, может, слить его в development для более удобного тестирования на транке?

**Comment by AJFly** [comment]
@Orhideous Было бы хорошо. Или мерж скоро? (Будет ли?)

**Comment by Orhideous** [comment]
@zluca Сделай, пожалуйста, pull-request :smile:

**Comment by AJFly** [comment]
@Orhideous реквест на мерж?....

**Comment by zluca** [comment]
Ок. Сделал. =)

**Comment by Orhideous** [comment]
Можно тестировать на транке. Все последующие изменения и фиксы уже в `development`

**Comment by AJFly** [comment]
@zluca Посмотел.
Ну, относительно удобно. 
Единственное, теперь надо как-то обозначить, что "Wide Mode" теперь - переход между экранами. 
Хоть ты тут это и написал, простые юзеры не сразу поймут. 

Вот как все выглядит: [раз](http://i.imgur.com/xRPSlyI.png), [два](http://i.imgur.com/te2Yk8m.png), [три](http://i.imgur.com/OUAXP2o.png), [четыре](http://i.imgur.com/kvphvQv.png), [пять](http://i.imgur.com/YEoKWY3.png).

И, кстати, [это](http://i.imgur.com/zpEgoZf.png) отделение аватара от заголовка - фича такая?)

**Comment by zluca** [comment]
> И, кстати, это отделение аватара от заголовка - фича такая?)

Да, когда заголовок слишком длинный он в несколько строк идёт. С линией красивее
<img src="https://cdn.everypony.ru/storage/02/43/83/2016/10/20/429f451e15.png" />
<img src="https://cdn.everypony.ru/storage/02/43/83/2016/10/20/fffed755ee.png" />
Ну по крайней мере мне так кажется что красивее =)

> Единственное, теперь надо как-то обозначить, что "Wide Mode" теперь - переход между экранами. 

Да я уже думал об этом. Может вообще её переименовать? Или картинку вешать в зависимости от разрешения.

> Вот как все выглядит

А в горизонтальном положении?

**Comment by AJFly** [comment]
@zluca 
> А в горизонтальном положении?

Прошу: [1](http://i.imgur.com/r1tlAZK.png), [2](http://i.imgur.com/z6e874j.png), [3](http://i.imgur.com/TwRMSEo.png)
А вот [тут](http://i.imgur.com/IpnJKqX.png) показан большой белый зазор между хеддером и футтером.

**Comment by AJFly** [comment]
> Может вообще её переименовать? 

И на декстопе тоже переименуется? Или 2 разные версии будут? 
Если 1-е, то лучше как-то обозначить (значком или еще как-то), и в FAQ отметить.
Если 2-е, то переименовать.

**Comment by zluca** [comment]
> белый зазор между хеддером и футтером

Потому что высота выставлена по боковой панельке. Обычно она меньше основного экрана, но тут наоборот вышло.

> И на декстопе тоже переименуется? Или 2 разные версии будут?

Пока рабочая версия (у меня в голове) напихать внутрь кнопки кучу спанов с разными надписями и показывать их в зависимости от разрешения и выбранного режима.

**Comment by AJFly** [comment]
Хорошо. Но в FAQ лучто все равно  уточнить.

**Comment by AJFly** [comment]
Думаю, сюда вставить лучше всего...
[http://i.imgur.com/d6yhq43.png](http://i.imgur.com/d6yhq43.png)

Так задумано?

**Comment by zluca** [comment]
Ммм, наверное, а что не так?

**Comment by AJFly** [comment]
"Войти" под "Зарегистрироваться".  Раньше было на одной строке. 
Обычно такое проявлялось на мобилках, но это - десктоп.

**Comment by roman901** [comment]
https://goo.gl/photos/MCPJcoCkcxEPZXtt9
"Войти" и "Зарегистрироваться" вообще нету.

**Comment by zluca** [comment]
@roman901 оно на боковой панельке спрятано. Нажми вайдмод кнопочку. =)
@Ajaxy 
> но это - десктоп

А, понял. Пофиксю.

**Comment by roman901** [comment]
@zluca ваще не очевидно

**Comment by zluca** [comment]
@roman901 согласен. =) Но мы ж не завтра на лайв заливаем, есть время подумать как лучше.

**Comment by zluca** [comment]
Так, на транк всё залилось. Кто-нибудь заметил новую панельку внизу? Как оно вообще?

**Comment by lunavod** [comment]
А можно ссылку на транк?

**Comment by zluca** [comment]
[транк](https://tabun-trunk.everypony.org/) - только надо пароль у Орхида выпросить. =)

**Comment by lunavod** [comment]
Ага, спасибо. Он, кстати, как оказалось, находится даже через гугол. :D

**Comment by zluca** [comment]
```
Script failed with status 255
failed to deploy
```
@Orhideous опять поломалось!
