### ISSUE TITLE
Кнопки "Написать письмо" и "Вступить в блог"

### ISSUE THREAD

**Issue by zluca** [everypony/tabun#72]
### Проблема
[битбакет](https://bitbucket.org/Orhideous/tabun/issues/23/)
При наведении курсора на данные кнопки вылазит надпись, которая резко увеличивает размеры кнопки тем самым нарушая вёрстку.

### Решение
Вариант 1 - перенести надпись в title кнопки. Будет вот так:
<img src="https://cdn.everypony.ru/storage/02/43/83/2016/10/05/b307f14e16.png" />

Вариант 2 - увеличить базовый размер кнопки. Будет вот так:
<img src="https://cdn.everypony.ru/storage/02/43/83/2016/10/05/a306901f68.png" />

**Comment by roman901** [comment]
Я за вариант 1, более адекватный.

**Comment by zluca** [comment]
Да мне самому он больше нравиться. =)

**Comment by zluca** [comment]
Помимо прочего пришлось по ходу пофиксить ещё и [это](https://bitbucket.org/Orhideous/tabun/issues/152/)
