### ISSUE TITLE
Отвязать Табун от формирования абсолютных ссылок

### ISSUE THREAD

**Issue by Orhideous** [everypony/tabun#74]
Это понадобится в будущем, при необходимости менять домен.

**P.S. Важность первоочередная**

**Comment by roman901** [comment]
А конкретнее, это как? Везде ссылки изменить на {router page=""}, а сам функционал роутера сделать в виде формирования ссылки без домена?

**Comment by zluca** [comment]
Вот мне больше интересно что будет со всеми линками в постах/комментах что юзеры понаписали. Это всё подменять?

**Comment by Orhideous** [comment]
@roman901 Да, нужно залезть в ядро роутера и формировать ссылки без домена.
@zluca Такого рода обратная совместимость обеспечивается nginx'ом.

**Comment by roman901** [comment]
так изи же.

**Comment by roman901** [comment]
Исправлений не требуется, имя домена нигде не прописывается, так то.

**Comment by NeatSketch** [comment]
В шапку сайта гляньте.
В файле `templates/skin/synio/header_top.tpl` дважды встречается `tabun.everypony.ru`.
