### ISSUE TITLE
Иконки MarkItUp

### ISSUE THREAD

**Issue by zluca** [everypony/tabun#76]
Сейчас на Табуне 29 иконок вида edit-*.png. Неплохо бы их в спрайт засунуть. В теории должна увеличиться скорость загрузки страниц и уменьшиться нагрузка на сервер.

Ничего сложного, но подожду как Орхи даст отмашку.

**Comment by Orhideous** [comment]
Хорошо! Ибо пока не у всех есть HTTP/2
