### ISSUE TITLE
Вернуть цитирование при выделении

### ISSUE THREAD

**Issue by zluca** [everypony/tabun#77]
[битбакет](https://bitbucket.org/Orhideous/tabun/issues/168/)

Рабочий код уже есть. Когда Орхи примет (или нет) предыдущие коммиты сяду переписывать на кофе.

**Comment by lunavod** [comment]
BTW: Почему не :bofore и :after?

**Comment by zluca** [comment]
Считаю псевдоклассы костылём и по возможности не использую.

**Comment by zluca** [comment]
Оказывается в Хроме всё не как у людей работает:
<img src="https://cdn.everypony.ru/storage/03/42/62/2016/10/17/259bde3228.png"/>
- починить

Оказывается редактирование комментрария идёт в другой форме.
- как-то разрулить

**Comment by zluca** [comment]
@Orhideous а ты будешь до 1.3 откатывать или прям вот щас срочно всё чинить? =)

**Comment by undertroll** [comment]
@zluca срочно чинить.
Никто до 1.2. откатывать не будет.

**Comment by zluca** [comment]
@undertroll 1.3. Просто цитирование в 1.4 должно было попасть. А сейчас теоретически 1.3 должен стоять.

**Comment by undertroll** [comment]
Ну насколько реалистично срочно починить? Ты сможешь?

**Comment by zluca** [comment]
Вообще могу конечно и срочно, это ж мой код. =) Срочно в смысле сегодня, а не прямо сейчас.
