### ISSUE TITLE
Работа с комментариями

### ISSUE THREAD

**Issue by zluca** [everypony/tabun#78]
Некоторые вещи при работе с комментариями на Табуне реально бесят. Раньше я их фиксил разными сторонними костылями, а тут можно прямо в исходники фигачить. Так почему бы и да? =)
- при заходе в топик первый раз комменты не подсвечиваются как новые
- автообновление комментов (тут надо думать над допустимым интервалом)
- счётчик новых комментов в заголовке. Например вот так:
  <img src="https://cdn.everypony.ru/storage/02/43/83/2016/10/10/61d63316e2.png" />
- при обновлении комментов убирает класс "новые" у всех комментов и сбрасывает счётчик. С автообновлением это несовместимо, надо фиксить
- хоткеи для листания новых, чтобы мышку не мучить
- листалка не центрирует комментарий, а надо бы

**Comment by lunavod** [comment]
> при заходе в топик первый раз комменты не подсвечиваются как новые

А зачем?

> листалка не центрирует комментарий, а надо бы

Это как?

**Comment by zluca** [comment]
> А зачем?

Чтобы их листать кнопочкой.
> Это как?

От верха экрана до коммента и от низа до коммента должны быть одинаковые зазоры. Или если коммент слишком длинный и не влазит в экран то размещаем его вверху экрана.

**Comment by lunavod** [comment]
> Чтобы их листать кнопочкой.

Так а смысл, если проще прокрутить? Они ж все новые тогда. Листать кнопочкой имеет смысл, когда новые в разных местах.

**Comment by zluca** [comment]
> Листать кнопочкой имеет смысл

Всегда если есть хоткей и центрирование + можно сделать автораскрытие спойлеров.
Кстати, из всего списка это единственная вещь которую не прикрутишь костылями со стороны клиента (тем и бесит).

**Comment by undertroll** [comment]
1. Хочешь -- запили. Но согласуй как это будет выглядеть.
2. Скрипт есть, но можешь опять же запилить сам. Если нет, то хотелка неуместна.
3. Аналогично есть скрипт.
4. Проблема. Опять же, чинишь сам или хотелка неуместна.
5. Опять же чинится скриптом. На пробел перелистывает. 
6. Ну ты немного офигел уже с хотелками.

Короче, скажи, сможешь ли что сделать сам. Если нет, то хотелку я удаляю.

**Comment by zluca** [comment]
> сможешь ли что сделать сам

Да я уже сделал. =) Надо только по кофе переписать.

**Comment by undertroll** [comment]
Тогда скрины нужны как все реализовано в студию.
Ну и переписывай, да. Другой никто не перепишет.

Хотя 6 не нужно.

**Comment by lunavod** [comment]
> Всегда

Ну фиг знает. Я наоборот, если комментов мало, листалку не юзаю. В идеале это стоило бы сделать отключаемым. =/

**Comment by zluca** [comment]
> Тогда скрины нужны как все реализовано в студию.

Так это всё логика работы скриптов клиента. Интерфейс никак не поменяется. (ну кроме счётчика в заголовке, но его то я заскринил)

> Ну и переписывай, да.

Надо одобрение Орхи, а то хрен его знает не положат ли Табун юзеры если у всех сразу автообновление заработает.

> В идеале это стоило бы сделать отключаемым. =/

Так скролл то у тебя никто не заберёт. =)

**Comment by roman901** [comment]
@undertroll что плохого в том чтоб хотеть кастомизацит ui? Почти за все за, смысл плодить сторонние скрипты если можно уже интегрировать

**Comment by undertroll** [comment]
@roman901 Я к тому, что если это просто "хочу", то мимо. Слишком много надо сделать более важного.
Однако если это "Я хочу и я сделаю", то тогда уместно.

**Comment by roman901** [comment]
@undertroll даже если просто "хочу", то пусть себе валяется в трекере - кому то станет скучно и сделают.

**Comment by undertroll** [comment]
Так, я уже просто не знаю как достучаться до Орхида, а потому оффтопик:
@Orhideous загляни, **пожалуйста**, в скайп.

**Comment by roman901** [comment]
Орхид на работе, по вечерам _иногда_ заходит

**Comment by undertroll** [comment]
С четверга не видал. Сегодня уже ЕП ложить надо на ночь. И еще кучка дел.

**Comment by zluca** [comment]
Запилил пока отдельным бранчем, кому интересно может потестить. Пока реализовано так:

- при первом заходе все комменты новые (если я ничё не поломал со стороны сервера :D)
- счётчик новых в заголовке как на скрине в начале темы
- хоткеи: space || ins - листалка, enter || del - обновлялка (при открытом редактировании не срабатывают)
- обновлялка сбрасывает новые если жмакать мышкой или хоткеем, а при автообновлении нет
- автообновление срабатывает раз в минуту, но только в неактивных вкладках и если не открыта форма редактирования.

**Comment by AJFly** [comment]
Ну что, как тестить?)

**Comment by zluca** [comment]
Я пока не мержил. И потом надо активных флудеров на транк, а то понятно будет работает или нет. =)

**Comment by AJFly** [comment]
А это надо дождаться, чтобы транк стал не только девом.
Хотя, я считаю, что транк - только для техотдела. 
@Orhideous, ведь так? 

С другой стороны, без людей не проверить...

**Comment by roman901** [comment]
Набить самим. Или же нагенерить, я так обычно делаю

**Comment by zluca** [comment]
Придумал ещё вот такую штуку для нормального чтения длинных веток:
<img src="https://cdn.everypony.ru/storage/02/43/83/2016/10/23/c56d470e10.png" />
Родительский коммент будет всегда сверху от текущего. Фактически можно хоть вообще отступы убрать если захочется. Особенно актуально для мобилок где лесенку особо не порисуешь из за малой ширины экрана.

**Comment by undertroll** [comment]
Едва ли нужно. Разве что потом добавить фичу для настраиваемого UI, а до тех пор не трогать. Я про длинные ветки.

**Comment by lunavod** [comment]
На пикабу неплохая система у длинных веток.

**Comment by zluca** [comment]
> На пикабу неплохая система у длинных веток.

Так там так и сделано - жмакаешь "показать ветку" и все промежуточные комментарии между текущим и родительским сворачиваются.

**Comment by lunavod** [comment]
Разве? Вроде там в конце длинных веток кнопка "развернуть дальше", и комментарии дальше идут с выделением, но с сильно меньшим отступом, начиная где-то с середины по ширине. Промежуточные остаются.

**Comment by lunavod** [comment]
![2016-10-26 11-18-36](https://cloud.githubusercontent.com/assets/14801311/19718498/367f6796-9b6e-11e6-967b-61a2d593a54c.png)
![2016-10-26 11-19-12](https://cloud.githubusercontent.com/assets/14801311/19718499/3681b186-9b6e-11e6-9870-68e76f56b5fb.png)

**Comment by zluca** [comment]
В комментарии кнопка в виде ветки - вот она сворачивает, похоже как и у меня. Только я хочу чтобы при листании новых комментов сразу по умолчанию срабатывала, так гораздо удобнее сразу видишь к чему коммент относится.

**Comment by zluca** [comment]
Вот [тут](https://bitbucket.org/Orhideous/tabun/issues/63/) @NeatSketch жаловался на анимацию прокрутки комментов. Попробовал ради эксперимента совсем её отключить - мне так даже больше понравилось. Та что сейчас используется - стандартная анимация из жКвери не такая уж и плавная.

@everypony/tabun что думаете?

И ещё нужны ли реально фолдинги?

**Comment by lunavod** [comment]
Ящитаю, анимация таки нужна. Хоть такая, как сейчас. 

Фолдинги нужны, но рачбочие, и чтобы в свернутые ветки не приходили новые комменты. Вернее, чтобы они туда добавлялись, но в счетчике новых их не было. В идеале еще нужно их запоминать, но это совсем в идеале.

**Comment by NeatSketch** [comment]
@zluca @lunavod Раз кому-то нужна, кому-то нет, давайте действительно добавим опцию-выключатель анимации.

**Comment by andreymal** [comment]
@zluca [зачем goto-comment-child отломал?](https://github.com/everypony/tabun/commit/ee5339767986b3638628fcd5463b76378a3a21cd)
