### ISSUE TITLE
Допуски на голосование

### ISSUE THREAD

**Issue by zluca** [everypony/tabun#79]
После обновления все настройки сбились. Причина как я понимаю вот [здесь](https://github.com/everypony/tabun/blob/development/settings/parts.d/module.magicrule.php).

**Comment by undertroll** [comment]
Нужно просто убрать правило о том, что голосовать можно только после создания поста. Табун немного не то место, такое не надо.

**Comment by zluca** [comment]
Да там и пороги кармы кривые и по времени создания аккаунта.

**Comment by undertroll** [comment]
Например? Я чукча, мне код лень пытаться прочесть. Я язык не знаю.

**Comment by zluca** [comment]
Да там и без знания языка понятно.

```
    'rule' => [
        'vote_comment' => [
            'msg' => 'Вы ещё недостаточно окрепли!',
            'groups' => [
                [
                    'registration_time' => 60 * 60 * 24, <== сутки после регистрации
                    'rating' => -5,                    <== голосование с откицательной кармой
                    'count_comment' => 2,             <== нужно 2 коммента
                    'count_topic' => 1                    <== и 1 пост
                ]
            ]
        ],
```

**Comment by undertroll** [comment]
А вот сутки нужны.

Кстати, отрази это в FAQ тоже, пожалуйста.

**Comment by zluca** [comment]
> Кстати, отрази это в FAQ тоже, пожалуйста.

Я его уже 10 раз переделывал. Может сначала определится окончательно какие и где ограничения, а потом уже фак?

**Comment by undertroll** [comment]
Допуск на голосование... Раньше же все ограничивалось силой, разве нет? Сколько её там надо.

**Comment by zluca** [comment]
Раньше было ограничение чисто по карме. Последнее значение до апдейта было 25. Так в правилах и факе и записано.

**Comment by undertroll** [comment]
И за комменты тоже?

**Comment by Orhideous** [comment]
@zluca Если что: все хотфиксы, которые надо выкатить в мастер, пушайте в ветку `hotfix`, и при необходимости (а она почти всегда будет) коммиты из нее мержите *в* `development`.

**Comment by zluca** [comment]
@undertroll раньше было одинаково. А сейчас по идее можно по хитрому настроить.
@Orhideous Окей. =)

**Comment by undertroll** [comment]
Короче, сутки оставить. 
А еще добавить 25 кармы для голосования и для комментов тоже.
И отразить все в ФАК.

**Comment by zluca** [comment]
А количество комментов и постов убирать?

**Comment by undertroll** [comment]
Да. Один хрен карму наклопать сложнее чем 2 коммента.
