### ISSUE TITLE
Не работает регистрация

### ISSUE THREAD

**Issue by lunavod** [everypony/tabun#85]
При попытке зарегистрироваться, при корректном заполнении полей и пройденой капчей, все равно возвращается ошибка "вы робот", но при этом не отображается в интерфейсе.

**Comment by Orhideous** [comment]
Проблема с корневыми сертификатами гугла, будет решено в ближайшие ≈12 часов

**Comment by Orhideous** [comment]
Да, действительно, бандл корневых сертификатов устарел. Перевел на системный.

**Comment by zluca** [comment]
Ну по крайней мере на транке рега пошла. =)
