### ISSUE TITLE
JQuery и привязанности

### ISSUE THREAD

**Issue by EpicMan2** [everypony/tabun#86]
Вероятно, до сих пор остались где-то строгие привязанности к JQuery, создающие такие вот проблемы "Нажимаю на ссылку "загрузить фото" и ничего не происходит".

В свою очередь консоль указывает на то, что JQuery отсутствует вовсе "Uncaught ReferenceError: jQuery is not defined".

**Comment by Orhideous** [comment]
Это, скорее, относится к #2 
Допишу там как пункт, спасибо.
