### ISSUE TITLE
Настраиваемый UI

### ISSUE THREAD

**Issue by undertroll** [everypony/tabun#87]

**Comment by undertroll** [comment]
@zluca Твое же детище, так?
Вот ты и убирай.

**Comment by Farxial** [comment]
Как вариант, можно
A. Добавить её сбоку/снизу коммента
B. Выполнить цитирование при нажатии кнопки Ответить

**Comment by AJFly** [comment]
@Farxial 

> B

А если не хочешь выделять?

**Comment by Farxial** [comment]
@AJFly
Тогда пусть ничего не цитируется? ![f8c7fb](https://files.everypony.ru/smiles/1b/93/f8c7fb.png)

**Comment by AJFly** [comment]
Ну... Дыа?..

**Comment by zluca** [comment]
В целом всё заработало как я и задумывал. Так что закрываю.
