### ISSUE TITLE
Вернуть отображение списка самых щедрых брони

### ISSUE THREAD

**Issue by Orhideous** [everypony/tabun#89]

**Comment by zluca** [comment]
Аноны без аватарок выбиваются из списка:
<img src="https://cdn.everypony.ru/storage/02/43/83/2016/10/19/774863ab3e.png" />

**Comment by zluca** [comment]
Вот так будет после фикса:
<img src="https://cdn.everypony.ru/storage/02/43/83/2016/10/19/a2ea470564.png" />

**Comment by zluca** [comment]
Народ [жалуется](https://bitbucket.org/Orhideous/tabun/issues/337/) что список слишком длинный. Можно добавить таких стилей:
```
  .donation-list>li{
    display: inline-block;
    width: 150px;
    overflow: hidden;
  }
```
Будет отображаться в 2 колонки на широких экранах:
<img src="https://cdn.everypony.ru/storage/02/43/83/2016/10/23/25b63365a6.png" />

**Comment by undertroll** [comment]
Поддерживаю. Я уже поднимал вопрос в ЛС Орхида.
Убрать аватарки или сделать топ-10.

**Comment by Orhideous** [comment]
Так, уменьшил количество до 10, потом будет динамическое, ±2 пользователя
