### ISSUE TITLE
Баннер на сайдбаре

### ISSUE THREAD

**Issue by zluca** [everypony/tabun#93]
### Проблема
Использование слов banner ad ads и тому подобных в пути к картинкам вызывает агро банерорезок:
<img src="https://cdn.everypony.ru/storage/02/43/83/2016/10/19/4be00bf605.png" />

### Решение
Переименовать путь во что-нибудь нейтральное

### Дополнительно
Также для пущей красоты предлагаю добавить
```
    .block-type-banner img{
        width: 100%;
    }
```

**Comment by Orhideous** [comment]
Решено не в рамках кода.
