### ISSUE TITLE
Написать инструкции для запуска окружения разработчика, отличного от контейнеров vagga

### ISSUE THREAD

**Issue by Orhideous** [everypony/tabun#97]
Нужно, как минимум, описать:
- [ ] запуск на чистой машине, нативно (Ubuntu 16.04)
- [ ] запуск на macOS, через brew
- [ ] запуск в контейнерах Docker

Специфичные для vagga **ad-hoc** команды нужно портировать на Makefile.

**Comment by zluca** [comment]
В общем переехал я с Минта на Арч и тут оказалось что там в ядре какой-то флаг не так стоит, в результате для запуска вагги надо кернел пересобирать.

@Orhideous а можно как-нибудь без всех этих докеров просто статику собрать?

**Comment by Orhideous** [comment]
@andreymal Там ничего _кардинально нового_ не появилось; зависимости те же, порядок разворачивания тот же.

**Comment by KarelWintersky** [comment]
А давайте просто в организации everypony создадим репозиторий wiki или howto и сложим туда все доки по разворачиванию? 

Можно будет сделать что-нибудь в духе https://github.com/RPGCodeBase/RPGCodeBase.github.io (джекил)

**Comment by Orhideous** [comment]
Тут документации не так много; есть, впрочем, [CONTRIBUTING.md](https://github.com/everypony/tabun/blob/development/CONTRIBUTING.md), и если его станет не хватать, то я совершенно не против вики прямо тут.

**Comment by roman901** [comment]
Добавлю, что первоначальное разворачивание проекта на OS X "нативными" серсивами у меня занимало в районе 30 минут.

**Comment by KarelWintersky** [comment]
@Orhideous, это нужно в первую очередь для того, чтобы всю документацию, сколь мало бы её ни было - собрать в одну кучу. Просто удобство. 

Просто создай вики ;)

**Comment by Orhideous** [comment]
@KarelWintersky https://github.com/everypony/tabun/wiki

**Comment by Orhideous** [comment]
Obsolete due to #173.

**Comment by andreymal** [comment]
А вот щас обидно было
