### ISSUE TITLE
Перенаправление в "Ты всё равно ещё вернёшься"

### ISSUE THREAD

**Issue by NeatSketch** [everypony/tabun#98]
Находясь на сабжевой странице, пользователь может передумать и захотеть снова залогиниться.
Ему мешает перенаправление, которое выкидывает со страницы через несколько секунд.
Чтобы этого не происходило, предлагаю отменять перенаправление в случае открытия формы логина (или регистрации).
Либо вовсе убрать перенаправление, так как в нём так или иначе нет смысла.

**Comment by AJFly** [comment]
Да, согласен, давно об этом писал на Битбакете. [#79 - hacking attempt](https://bitbucket.org/Orhideous/tabun/issues/79/http-tabuneveryponyru-login-exit)

**Comment by Orhideous** [comment]
Да, страницу убрать, вместо нее отдавать просто главную.

**Comment by Orhideous** [comment]
@NeatSketch поможешь?

**Comment by NeatSketch** [comment]
@Orhideous Ок
