### ISSUE TITLE
Добавить ссылку на "Опрос" в окне "Создать" и на странице создания; добавить все FAQ по тегам под спойлер или еще куда.

### ISSUE THREAD

**Issue by AJFly** [everypony/tabun#99]
1) Про [это FAQ ](http://i.imgur.com/9Grp975.png)я говорил. Пока долистаешь до "Опубликовать", чокнуться можно.

2) Вот в [это окно/поле](http://i.imgur.com/I1sPd4F.png)добавить "Опрос", просто для удобства и быстрого перехода.

3) Помню, что [тут были](http://i.imgur.com/5EaRyhI.png) 2 ссылки - "Пост" и "Опрос". Хотелось бы вернуть. Опять же - для лишнего удобства. Понятно, что можно тыкнуть на слово "пост", но все же.

**Comment by zluca** [comment]
2) На мобилах не влезет в экран
<img src="https://cdn.everypony.ru/storage/02/43/83/2016/10/20/5d320981e5.png" />

**Comment by AJFly** [comment]
Тогда можно реализовать п. 1 и 3.

**Comment by roman901** [comment]
С мобил посты в основном и не создают. Плюс можно просто уменьшать масштаб.

**Comment by AJFly** [comment]
Если мобильная тема войдет в жизнь, то уменьшить не получится.

**Comment by zluca** [comment]
Пункт 1 сделал - помощь по тэгам закрыта по умолчанию. Остальное... спорно.

**Comment by undertroll** [comment]
Чем-то более полезным займитесь лучше.
Это вот сейчас какое-то переливание из пустого в порожнее.

**Comment by Orhideous** [comment]
Это будет в рамках переработки редактора, к этой задаче вернемся, как будем пилить автокомплит
